### ISSUE TITLE
Option `--ignore-osmosis-headers` changes replication tool behavior

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#102]
I was just playing around with the new tools for replication handling and stumbled upon this: it looks like using the flag `--ignore-osmosis-headers` on a Geofabrik extract (with osmosis headers in them) completely changes the way the tool behaves:
- using the flag downloads ~23 MB of changes
- not using the flag downloads not a single change

I was expecting the flag to not have any effect since the different ways of determining timestamp/sequence numbers where to continue from should in the end result in the same changes to be downloaded - or is my mental model wrong here?

Small snippet for replication (heh):

```bash
wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf

pyosmium-get-changes -O berlin-latest.osm.pbf --ignore-osmosis-headers 
ERROR: HTTP Error 404: Not Found
3411437

pyosmium-get-changes -O berlin-latest.osm.pbf
2187
```

Then using the `-o` option writes different outfiles:
- in the case of providing the flag I'm seeing the 404 error and a 23 MB change file
- in the case of not providing the flag I get an empty change file

**Comment by daniel-j-h** [comment]
Same problem with the `pyosmium-up-to-date` tool.

Side note: is the default replication url not valid, or why are we getting a 404 here?

**Comment by lonvia** [comment]
The 404 is bogus and can safely be ignored. It is a result of #67. I really should be fixing that.

For the rest, the behaviour is entirely expected. The replication headers contain the exact osc ID to start replications with. When you download an extract, then it is up to date and will report the osc ID for the next day. So an immediate update, doesn't do anything (Ihope you get an error an not an empty file).

When you ignore the replication header, pyosmium needs to compute the osc ID from the date of the newest change. It is a bit conservative and uses a date that is a couple of hours earlier. The result is that you get the osc from the day where you downloaded the diff. The resulting updated extract should be almost exactly the same (minus some odd artefacts on the boundary).

**Comment by daniel-j-h** [comment]
Interesting, thanks for the explanation!

> When you download an extract, then it is up to date and will report the osc ID for the next day.

Is the osc id always on the "finest" granularity? That is, if I download a Berlin snapshot _right now_, wait ten minutes, and then use the provided tools here to fetch/apply the latest minutely changes, will I get changes for Berlin from the last ten minutes?

> When you ignore the replication header, pyosmium needs to compute the osc ID from the date of the newest change. It is a bit conservative and uses a date that is a couple of hours earlier.

Do I understand this correctly: 
- if there is an osc id in the metadata we use that, otherwise
- we can walk over the provided `.osm.pbf`, figure out the latest object's timestamp, and then fetch changes for a few hours earlier

Why a few hours earlier? Because there might have changes the `.osm.pbf` might not have picked up due to _reasons_? Is there no other way to derive the changeset state a snapshot is on?

> So an immediate update, doesn't do anything (Ihope you get an error an not an empty file).

I got an empty .osc.gz file - no visible error.

**Comment by daniel-j-h** [comment]
Okay forget what I said, turns out we are using the metadata replication server by default. And the Geofabrik snapshots are providing the following endpoint:

    osmium fileinfo --get header.option.osmosis_replication_base_url berlin-latest.osm.pbf 
    http://download.geofabrik.de/europe/germany/berlin-updates

Which does not give us minutely updates.

Therefore the empty .osc.gz file is expected here.

If I supply `--ignore-osmosis-headers` we ignore both:
- the bakes in osc id
- the baked in replication endpoint

and all is good :)

**Comment by lonvia** [comment]
You can also explicitly supply the replication source to use with `--server`. That overrides the replication headers as well. pyosmium-up-to-date also allows to set more precisely how far to go back from the last found change with `--wind-back`. pyosmium-get-changes oddly enough doesn't seem to have that option. And finally you can also set `--start-date`, if you are not happy with the dates that pyosmium computes.

Note that pyosmium-get-changes is meant to be used like that: first you run it without the `-o` parameter but with `-D` or `-O` to get the sequence number where you want to start from (printed to stdout). After that you always run it with `-o` and `-I` to produce updates. Or even easier: 

```
pyosmium-get-changes -O planet.pbf -f last-change.id
while true; do
    if pyosmium-get-changes -o changes.osc.gz -f last-change.id; then
        # do stuff with changes.osc.gz here
    fi
    sleep 10
done
```

Be careful with the replication source though. The first call to pyosmium-get-changes might use an implicit one from the input file, the second always uses the default minutely replicates.

> I got an empty .osc.gz file - no visible error.

It doesn't say anything but you should get a different return value from the application. The empty diff file might have been on purpose to not make a subsequent call to something else crash but I'm not sure.

**Comment by daniel-j-h** [comment]
Dope, this helps a lot! :bowing_man: 

I'm closing this as user-error and not actionable on your side. Maybe we can add a bit of information from the conversation above to the docs but otherwise we're good here.

Thanks!
