### ISSUE TITLE
pyosmium-up-to-date objects in output seem to heavily depend on replication server

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#103]
Let's say I downloaded the latest Berlin snapshot from Geofabrik. It's about 53 MB.

By default the Geofabrik snapshot includes its own replication server in the osmosis metadata.

```bash
osmium fileinfo --get header.option.osmosis_replication_base_url berlin-latest.osm.pbf 
http://download.geofabrik.de/europe/germany/berlin-updates
```

I want to overwrite this replication server to always update the Geofabrk snapshot with the latest minutely diffs.

```bash
pyosmium-up-to-date berlin-latest.osm.pbf -o berlin-latest-uptodate.osm.pbf --server 'https://planet.osm.org/replication/minute/' --ignore-osmosis-headers
```

The resulting `.osm.pbf` now is about 118 MB in size.

In contrast if I call `pyosmium-up-to-date` without the `--ignore-osmosis-headers` to fetch diffs from the Geofabrik replication server baked into the `.osm.pbf` I get a new file which is only a couple of kilobytes bigger than the original one (which makes more sense to me).

Here are the object diffs for
- using the minutely diff replication server
- using the baked in Geofabrik replication server

```
osmium diff berlin-latest.osm.pbf berlin-latest-uptodate-minutely.osm.pbf -s -q
[======================================================================] 100% 
Summary: left=1311 right=6189443 same=5999552 different=6

osmium diff berlin-latest.osm.pbf berlin-latest-uptodate-osmosis.osm.pbf -s -q
[======================================================================] 100% 
Summary: left=683 right=1449 same=6000186 different=0
```

This behavior is a bit unexpected. Why does using the minutely replication server result in a file roughly twice the original size, compared to only a few kilobytes when using the Geofabrik replication server?

Am I doing something wrong here? :)

**Comment by joto** [comment]
The Geofabrik replication files contain only what's needed for the extract you are looking at (here Berlin). The replication diffs from planet.osm.org contain the data for the whole planet.

**Comment by daniel-j-h** [comment]
This means the replication server needs to be in sync with the area the snapshot was created from?

Is this a technical limitation or would it be feasible to fetch diffs from arbitrary replication servers?

Maybe we also should add this to the docs as it's not the expected behavior (at least in my mental model).

**Comment by joto** [comment]
In theory you can fetch diffs from any replication server, but that means that you get all the data that it delivers. If you get updates for the whole planet, it should be obvious that you not only get updates for some extract, but for the whole world and that's a lot of data. If you do it long enough, you'll have the data for the whole planet as new data is added and old data is replaced by new data, you get more and more of it. The way OSM data is organized and the way diffs are structured there is really no other way of doing this. So you usually need a replication server that fits your extract.

(Different replication servers can use different diff "serial numbers", not sure whether the ones from Geofabrik are in sync with the ones from planet.osm.org. This has to be taken into account.)

**Comment by daniel-j-h** [comment]
Okay this is is unexpected. But makes sense when even the sequence numbers can be out of sync.

Hrm, that's a bit ugly since the data snapshots are now bound to a single replication server - forever. If the replication server is gone so are any chances for updating snapshot. No guarantees for the future.

Are there any docs about this either for pyosmium and/or other sources? I didn't know about it at all.


Closing here already since the problem is not in pyosmium but rather the way diffs are bound to the snapshot and a specific replication server.

**Comment by lonvia** [comment]
> Hrm, that's a bit ugly since the data snapshots are now bound to a single replication server - forever. If the replication server is gone so are any chances for updating snapshot. No guarantees for the future.

That's not entirely true. You can always switch replication sources, you just have to reinitialise your sequence number using the date of the latest change to match the new source (exactly in the same way as you do when starting updates with --ignore-osmosis-headers). Normally diff consumers are replay-safe (I can guarantee it for pyosmium-up-to-date and osm2pgsql). That means that you can wind back the sequence and reapply all diffs and end up in a consistent state when done. That's why this works.

> Are there any docs about this either for pyosmium and/or other sources? I didn't know about it at all.

This is all generic knowledge about the OSM replication process. The pyosmium docs are not a good place to explain it.

**Comment by rory** [comment]
> Different replication servers can use different diff "serial numbers", not sure whether the ones from Geofabrik are in sync with the ones from planet.osm.org

They are not.

As of right now, the [Berlin state.txt file](http://download.geofabrik.de/europe/germany/berlin-updates/state.txt) is
