### ISSUE TITLE
ImportError: No module named osmium.replication

### ISSUE THREAD

**Issue by gordocabron** [osmcode/pyosmium#104]
Hi,

I closely followed the installation instructions for Nominatim 3.2.0. Early I have set up another server with Nominatim 3.1.0 and the updates where working fine. On the new server - on trying to get updates for a europe file with pyosmium started - I get the following error:

xxx@xxx:~$ sudo -u nominatim /srv/nominatim/Nominatim-3.2.0/build/utils/update.php --import-osmosis-all
Currently at sequence 2204 (31/03/2019 20:14:35) - t indexed
/srv/nominatim/.local/bin/pyosmium-get-changes --server https://download.geofabrik.de/europe-updates -o /srv/nominatim/Nominatim-3.2.0/build/osmosischange.osc -s 30 -I 2204
Traceback (most recent call last):
  File "/srv/nominatim/.local/bin/pyosmium-get-changes", line 27, in <module>
    from osmium.replication import server as rserv
ImportError: No module named osmium.replication
ERROR: updates failed.

The --init-updates executed under the nominatim user returns:

nominatim@xxx:~/Nominatim-3.2.0/build$ ./utils/update.php --init-updates
2019-04-04 21:52:49 == module path: /srv/nominatim/Nominatim-3.2.0/build/module
2019-04-04 21:52:49 == Create Functions
Summary of warnings:

2019-04-04 21:52:49 == Setup finished.
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
Done. Database updates will start at sequence 2204 (2019-03-31T17:14:35Z)

I haven't found a solution to this particular problem, yet. Any help would be greatly appreciated.

**Comment by lonvia** [comment]
When running under sudo for a different user you have to use `sudo -H` or python won't set the search path for the user-installed python libraries right.

**Comment by gordocabron** [comment]
Hey Ionvia,

thanks for the hint. It seems to be working now!

**Comment by Ash-47** [comment]
Hey @lonvia Even I'm getting the same error, I tried doing what you mentioned above, but it didn't help.

**Comment by lonvia** [comment]
Commenting on a 5 year old closed issue won't get you any help either. It's rather frowned upon by maintainers.

Go to the 'discussions' section, open a new post. If you want to get an answer, **do not** just throw your error message in the post. Describe what exactly you have been doing to get to the stage with your error: which OS you are on, how you installed pyosmium, what command you are executing etc.
