### ISSUE TITLE
Python __geo_interface__ support

### ISSUE THREAD

**Issue by MennoTammens** [osmcode/pyosmium#11]
__geo_interface__ is a protocol for Python libraries to exchange geospatial data
([A Python Protocol for Geospatial Data](https://gist.github.com/sgillies/2217756)).
The data is put in standard Python objects (dict,list,tuple,float) in a GeoJSON-like fashion.
It would be nice if pyosmium woud support this interface.

Geo Interface is already supported by a lot of other Python modules: Shapely, Fiona, ArcPy, descartes, geojson, PySAL, pyshp

Implementing this interface means adding a function __geo_interface__() to a number of classes in osmium.osm: Node, Way and Area, maybe also to Location, Box, NodeRef or NodeRefList.
Probabily something like GeoJSONFactory, but with _boost::python::dict_, _boost::python::list_, etc. instead of _std::string_

**Comment by joto** [comment]
This sounds like a useful addition. Maybe somebody who needs this themselves wants to give it a try?

**Comment by lonvia** [comment]
Implemented in #262.
