### ISSUE TITLE
How to add or change tag of a part of way.

### ISSUE THREAD

**Issue by hxm841946123** [osmcode/pyosmium#110]
Hi, I'm trying to finish my course project. Because some part of way are truck prohibited. But the OSM file does contain the information for that. So I have to add them. Is it possible that for a part of way, change access from yes to no by using coordinates and keep the others yes?  Please help me. Thank you.

**Comment by joto** [comment]
No, this is not possible, you have to split the way. And this is the wrong place to ask such questions. For beginner questions unrelated to PyOsmium go to help.osm.org.

**Comment by hxm841946123** [comment]
@joto Thank you so much for replying. Could you please give me some instruction of splitting a way? i'm really appreciate it.

**Comment by hxm841946123** [comment]
@joto Thank you so much. I have already know.
