### ISSUE TITLE
Segfault on apply_file

### ISSUE THREAD

**Issue by mattwigway** [osmcode/pyosmium#112]
If I `pip install osmium` into a fresh Python 3.7 or Python 2.7 conda environment on Mac OS X 10.14.5, I get a segfault when I run this code:

```python
import osmium
class Handler(osmium.SimpleHandler):
     def __init__ (self):
             pass
 
h = Handler()
h.apply_file('/Users/matthewc/Dropbox (ASU)/shopping/data/california-latest.osm.pbf')
``` 
=> `Segmentation fault: 11`

I tried to dump a core to get a stack trace, but I ran out of disk space before it finished (at about 100GB). I also tried with a much smaller PBF and had the same problem.

Interestingly, the segfault happens even if I pass in a filename that does not exist. So it's happening before it even tries to parse the file. It segfaults on the h.apply_file line; if I take that out the program completes.

Even if I install with `--no-binary osmium` I still get the segfault, but maybe the libosmium binary is still used?

**Comment by lonvia** [comment]
You are not initialising your handler correctly.  Constructors in Python need to call the constructors of inheriting classes. Try:

```
class Handler(osmium.SimpleHandler):
    def __init__(self):
        super(Handler, self).__init__()
```

**Comment by mattwigway** [comment]
Oof, my bad, thanks!
