### ISSUE TITLE
strange segfault when using pyproj

### ISSUE THREAD

**Issue by jmarca** [osmcode/pyosmium#116]
Not sure what I'm doing wrong here, but it seems importing both pyproj and pyosmium leads to a segfault.

Environment:
```
python --version
Python 3.7.4
 pip list
Package            Version    
------------------ -----------
...
osmium             2.15.3     
...
pyproj             2.4.0      
```

Code that segfaults

```python
import osmium
import pyproj

crs = pyproj.CRS.from_epsg(4326)
print(crs)
```
```bash
python pyproj_test.py
Segmentation fault
```

But if I switch the order of imports, no problem.

```python
import pyproj
import osmium

crs = pyproj.CRS.from_epsg(4326)
print(crs)
```

Obviously, the simple answer is to import osmium last!  But segfaults are bad, and I can't figure out why the order might matter.

**Comment by lonvia** [comment]
What system are you running on? Both pyosmium and pyproj use the libproj library and I suspect we are running into version issues here.

**Comment by jmarca** [comment]
I am using a Docker image that is based off the python 3.7 image. So whatever Ubuntu is inside of that. 

I can compile libproj et al from source. Would that be better? 

All I really want to do is transform geometries. Is there a call inside osmium to do that?

James

**Comment by lonvia** [comment]
It might help if you use the source wheel of osmium instead of the binary wheel.

**Comment by jmarca** [comment]
I'm sorry, I'm not familiar with what you mean by "source" versus "binary wheel".  Just educated my self a little bit:

my Dockerfile currently just says:

```
pip install --upgrade --no-cache-dir osmium sqlalchemy geoalchemy2 pyproj shapely
```

Should I change that to

```
pip install --upgrade --no-cache-dir https://github.com/osmcode/pyosmium/archive/v2.15.3.tar.gz
&& ...
```
etc for those libraries that link to proj?

I'll try it and see.

**Comment by jmarca** [comment]
Yep, looks like library versions are the problem.  Trying to build pyproj from source, it complains that it needs proj v6.2.0, but only 5.2.0 is installed  (python 3.7 image is based on buster).  So my guess is the binary pip install of pyproj included proj 6.2 or something.  I'll close this when I get everything compiled with same versions of proj and have verified no crashing.

**Comment by jmarca** [comment]
Okay, I fixed my Dockerfile to do the following:

Download proj 6.2.0 from source, build it;
pip install from source for both osmium and pyproj

Bug goes away...I can include libraries in whatever order.  

Relevant bits of Dockerfile (ultimately based on canonical python 3.7 image)

```
ENV PROJ_VERSION 6.2.0
RUN apt-get install -y sqlite3 \
        && wget -O proj.tgz "https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz" \
        && tar -xvf proj.tgz \
        && wget "https://download.osgeo.org/proj/proj-datumgrid-1.8.zip" \
        && unzip -o proj-datumgrid-1.8.zip -d proj-${PROJ_VERSION}/data/ \
        && cd proj-${PROJ_VERSION} \
        && mkdir build \
        && cd build \
        && cmake -DCMAKE_INSTALL_PREFIX=/usr .. \
        && make -j6 \
        && make install \
        && cd ../../ && rm -rf proj*

RUN pip install --upgrade --no-cache-dir --no-binary :all: pyproj osmium

# test the install
USER user

RUN python -c "import osmium as o; import pyproj as pp; crs = pp.CRS.from_epsg(4326); print (crs)"
RUN python -c "import pyproj as pp; import osmium as o; crs = pp.CRS.from_epsg(4326); print (crs)"
```

**Comment by lonvia** [comment]
Fixed with manylinux2020 binary wheels. Please be aware that a recent version of pip is needed. The one that ships with Ubuntu is too old.
