### ISSUE TITLE
How to break up a way into segments

### ISSUE THREAD

**Issue by jmarca** [osmcode/pyosmium#117]
I'm trying to break up ways into short segments.

The brute force way is to just grab the list of nodes and manually create linestrings between each pair of nodes from beginning to end.

But I'd like to stay in the idiom of pyosmium.  Trying to do something like the following for my way handler:

```python
def way(self, w):
    def edgeway(a,b):
        return osmium.osm.WayNodeList([a,b])
    highway = w.tags.get('highway')
    if highway is not None and highway in keep_ways:
        nodes = w.nodes
        edges = [{'start':nodes[a].ref,
                  'end':nodes[b].ref,
                  'edgeway':edgeway(nodes[a],nodes[b]),
                  'way':w.id}
                 for (a,b) in zip(range(0,len(nodes)-1),
                                  range(1,len(nodes)))]
        self.edge_list[w.id] = edges
```

but the interpreter complains that there is no constructor for `osmium.osm.WayNodeList([a,b])`

I was looking at https://github.com/osmcode/pyosmium/blob/master/test/test_geom.py and it seems that code creates ways by calling handlers on data.  That doesn't seem right here, as the nodes are already loaded into the parser and all I want to do is create a bunch of "mini ways" between each node pair in the way.

Forgot to say, the reason I want to do this is to be able to spit out linestrings for each edge segment.  So really just pumping the nodes' location pairs into shapely will probably do the trick.  I just wanted to try to stay inside of osmium.

**Comment by joto** [comment]
The Osmium datatypes (like `WayNodeList`) are special. They don't behave like normal Python data types in every respect. This allows PyOsmium to be so fast.

So for your case, you can just create a 2-element array, or, as you suggest, create a shapely object. Whatever is easiest to use for you. That's totally okay and the way to go here.

**Comment by jmarca** [comment]
Okay thanks.  I went with using shapely.
