### ISSUE TITLE
Get file info using Python

### ISSUE THREAD

**Issue by ssszyszkowicz** [osmcode/pyosmium#121]
I have been using pyosmium with much success (thank you for a very fine tool!). 

Can I access metadata information?
- Timestamp for the whole file
- File type (osm/pbf)
- Bounds
- etc.

The osmium console tool can give you these things, but I failed to find a way to obtain these through the Python bindings. Is it implemented?

**Comment by lonvia** [comment]
Pyosmium does not export osmium's file functions (timestamp, file type, etc). You'd have to use standard python function from the `os` module for those.

You can access the header of the OSM file to get bounds, etc. The following python script:

```
import sys
import osmium as o

f = o.io.Reader(sys.argv[1], o.osm.osm_entity_bits.NOTHING)

header = f.header()

print("Bbox:", header.box())
print("History file:", header.has_multiple_object_versions)
print("Replication base URL:", header.get("osmosis_replication_base_url", "<none>"))
print("Replication sequence number:", header.get("osmosis_replication_sequence_number", "<none>"))
print("Replication timestamp:", header.get("osmosis_replication_timestamp", "<none>"))
```

gets you:

```
> python3 info.py liechtenstein.osm.pbf
Bbox: (9.471078/47.047740 9.636217/47.271280)
History file: False
Replication base URL: http://download.geofabrik.de/europe/liechtenstein-updates
Replication sequence number: 2217
Replication timestamp: 2019-04-14T20:15:02Z
```
```

**Comment by ssszyszkowicz** [comment]
Thank you, this is very helpful. There is however, a hiccup: I am mainly interested in the osmosis_replication_timestamp. What you wrote works great for a .osm.pbf, but it doesn't seem to work for the xml (.osm) format (I get <none>), even though I can see timestamp="..." in the XML header.

Also, is it possible to identify the file type (XML vs PBF) in Python based on the contents, not the file name? I see that the console version of Osmium gives this information.

Is all this documented anywhere? It would be really useful if there was an example showing how to get at these values (if there is already, I am sorry, I couldn't find it).

Thank you again.

**Comment by joto** [comment]
The `osmosis_replication_timestamp` is reasonably clearly defined, the `timestamp` in the XML header not, so it isn't supported by libosmium. Most people use PBF files anyway because they are so much more performant.

The file type shown by the Osmium command line tool is based on the file name, Osmium doesn't do detection based on content.
