### ISSUE TITLE
TypeError: can't pickle osmium.osm._osm.Node objects

### ISSUE THREAD

**Issue by shindere** [osmcode/pyosmium#125]
While loading a `.osm.pbf`, I am trying to collect objects (nodes etc.)
in a Python list to process them later.

Simply appending them to the list gives a segfault. As I understand it
this is an expected behaviour because the objects are destroyed after
the handler they are passed to ends.

I hoped to resolve the problem by using the deep_copy module to add to
the lists not the objects themselves but rather a deep copy of them.

This is what gave rise to the message above.

I am kind of a newbie in Python so not able to know what should be done
to make the `osmium.osm._osm.Node` picklable.

Any help highly appreciated.

Thanks!

**Comment by lonvia** [comment]
There is no deep copy for the OSM objects and that's intentional. There are very few use cases where you need to save a complete object for later use. Ideally, you should do all of your computation directly in the callback. Where that is not possible, use native Python structures to save exactly the piece information that you need later.

I don't know your exact use case, so I cannot comment on what is the best strategy for you. For a generic example what I mean with minimizing what you save, have a look at the new section in the documentation that I've just merged with #124.

**Comment by shindere** [comment]
Dear Sarah,

First of all, many thanks for your prompt, nice and helpful response and
sorry for the delay of mine, I was off-line most of the time but now I
am back and hope to be more reactive.

Sarah Hoffmann (2020/02/02 06:15 -0800):
> There is no deep copy for the OSM objects and that's intentional.
> There are very few use cases where you need to save a complete object
> for later use. Ideally, you should do all of your computation directly
> in the callback. Where that is not possible, use native Python
> structures to save exactly the piece information that you need later.

Well, I guess it is indeed not always possible to do everything in the
callback, e.g. because, as I understand it, you don't know when loading
a node in which relations it will be or on which ways. I also asusme
that, when you see a way, nothing guarantees in the format that you have
already seen all the nodes it references, am I correct?

> I don't know your exact use case, so I cannot comment on what is the
> best strategy for you. For a generic example what I mean with
> minimizing what you save, have a look at the new section in the
> documentation that I've just merged with #124.

Will do, thanks.

To give one possible use-cas I may have, though, it's to be able to
extract a sub-map from the big one, because that's enough for my
application and it will then be easier and enought to just load that
submap. For such a use-case, I think I would rather not have to
remember, field by field, what I need to preserve. On the countrary, I
would really want to keep the objects as I loaded so that my submap is
as precise as possible and as similar to the original one as possible,
for the information I want to preserve.

Thanks!

**Comment by joto** [comment]
> I also asusme
that, when you see a way, nothing guarantees in the format that you have
already seen all the nodes it references, am I correct?

Almost all OSM files have first all nodes, then all ways, then all relations. So, yes, you know that all nodes are available when you see ways.

Also consider reading through an OSM file multiple times. Its seems like more work, but sometimes it makes more sense to read through the file once to figure out what data you need and only collect it on the second pass. But this depends very much on your use case.

> ...extract a sub-map from the big one...

Not sure what you mean by "sub-map". If you are talking about geographical extracts (only the data in some bounding box or so) then there are specialized tools that do that for you better and more quickly. No need to write this in Python. (See https://docs.osmcode.org/osmium/latest/osmium-extract.html ).

**Comment by shindere** [comment]
Jochen Topf (2020/02/12 04:21 -0800):
> > I also asusme
> that, when you see a way, nothing guarantees in the format that you have
> already seen all the nodes it references, am I correct?
>
> Almost all OSM files have first all nodes, then all ways, then all
> relations. So, yes, you know that all nodes are available when you see
> ways.

Okay, thanks.

> Also consider reading through an OSM file multiple times. Its seems
> like more work, but sometimes it makes more sense to read through the
> file once to figure out what data you need and only collect it on the
> second pass. But this depends very much on your use case.

I didn't think about that actually because the map I'm processing is a
bit large.

> > ...extract a sub-map from the big one...
>
> Not sure what you mean by "sub-map". If you are talking about
> geographical extracts (only the data in some bounding box or so) then
> there are specialized tools that do that for you better and more
> quickly. No need to write this in Python. (See
> https://docs.osmcode.org/osmium/latest/osmium-extract.html ).

No it's not a geographical area. It's rather a map with only some nodes
of interest and perhaps the ways and relations they are involved in.
