### ISSUE TITLE
test_osm.TestAreaFromWayAttributes fails on several architectures

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#13]
The Debian package build for pyosmium 2.7.1 failed on several architectures due to this test failure:
```
I: pybuild base:184: cd test && python2.7 run_tests.py
...........E...................
======================================================================
ERROR: test_func (test_osm.TestAreaFromWayAttributes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/test/helpers.py", line 104, in test_func
    self.Handler().apply_file(fn, self.apply_locations, self.apply_idx)
  File "/«PKGBUILDDIR»/test/test_osm.py", line 129, in area
    assert_equals(n.num_rings(), (1, 0))
TypeError: No to_python (by-value) converter found for C++ type: std::pair<unsigned int, unsigned int>

----------------------------------------------------------------------
Ran 31 tests in 0.340s

FAILED (errors=1)
```
Based on the list of architectures, it looks specific to 32-bit systems.

Full buildlogs: [armhf](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=armhf&ver=2.7.1-1&stamp=1464829191), [i386](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=i386&ver=2.7.1-1&stamp=1464819558), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=powerpc&ver=2.7.1-1&stamp=1464822308), [hppa](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=hppa&ver=2.7.1-1&stamp=1464823265), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=hurd-i386&ver=2.7.1-1&stamp=1464827379), [kfreebsd-i386](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=kfreebsd-i386&ver=2.7.1-1&stamp=1464822721), [x32](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=x32&ver=2.7.1-1&stamp=1464828825)

**Comment by sebastic** [comment]
Adding `std_pair_to_python_converter<unsigned int, unsigned int>();` as in the following patch seems sufficient to resolve this issue:
```patch
--- a/lib/osm.cc
+++ b/lib/osm.cc
@@ -50,6 +50,7 @@ BOOST_PYTHON_MODULE(_osm)
 
     to_python_converter<osmium::Timestamp, Timestamp_to_python>();
     std_pair_to_python_converter<int, int>();
+    std_pair_to_python_converter<unsigned int, unsigned int>();
     std_pair_to_python_converter<unsigned long, unsigned long>();
 
     enum_<osmium::osm_entity_bits::type>("osm_entity_bits")
```
With this change the test succeeds on the amd64 and i386 architectures, so I'll upload a new revision of the Debian package with this patch to verify it also resolves the issues for the other (32-bit) architectures.

**Comment by lonvia** [comment]
The change looks good. Do you mind creating a quick PR?

**Comment by sebastic** [comment]
FTR, the Debian package builds with the patch now succeeded on the architectures where the test failed before:

https://buildd.debian.org/status/package.php?p=pyosmium
