### ISSUE TITLE
How to load a history file?

### ISSUE THREAD

**Issue by linuxluigi** [osmcode/pyosmium#130]
Is it possible to load a history file with `SimpleHandler`?

When I use  a history file from https://geofabrik.de/ with `SimpleHandler` than I get the following error:
`RuntimeError: Way ID twice in input. Maybe you are using a history or change file?`

[Osmium-tool](https://osmcode.org/osmium-tool/manual.html#working-with-history-files) can handle history file, could it pyosmium too?

**Comment by lonvia** [comment]
History files should be working fine. Can you post the script your are trying to run?

**Comment by linuxluigi** [comment]
Python 3.8.2
osmium 2.15.4

I get the error with history & diff files.

With changeset files, it works fine.

Code:
```
from osmium._osmium import SimpleHandler
from osmium.osm._osm import Area, Node, Way


class OSMHandler(SimpleHandler):
    def __init__(self):
        SimpleHandler.__init__(self)


    def node(self, node: Node):
        pass

    def way(self, way: Way):
        pass

    def area(self, area: Area):
        pass


def run_import():
    osmhandler = OSMHandler()

    # scan the input file and fills the handler list accordingly
    osmhandler.apply_file(
        filename="/app/bremen-internal.osh.pbf",
        locations=False,
        idx="flex_mem"
    )

```

Output:
```
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/ohdm_django_mapnik/ohdm/management/commands/import_osh.py", line 10, in handle
    run_import()
  File "/app/ohdm_django_mapnik/ohdm/import_osh.py", line 24, in run_import
    osmhandler.apply_file(
RuntimeError: Way ID twice in input. Maybe you are using a history or change file?
```

**Comment by lonvia** [comment]
The `area` handler is the culprit here. It cannot be used together with history files. If you remove it, everything works fine. You can add a relation callback if you are interested in those kind of objects.

Background: The area callback gets geometries that are built implicitly from OSM way and relation objects. This requires looking up locations from nodes. In a history file there are multiple versions of a node and finding out which one to use is not trivial. So osmium doesn't have support for that.

**Comment by linuxluigi** [comment]
Thank you for detailed answer 🙂
