### ISSUE TITLE
pyosmium-up-to-date: disable pbf compression

### ISSUE THREAD

**Issue by Komzpa** [osmcode/pyosmium#131]
According to flamegraph most time in pyosmium can be spent in zlib.

https://docs.osmcode.org/osmium/latest/osmium-file-formats.html lists a way to avoid that:
to set output format option pbf_compression=false.

However, there's no obvious way to pass such option into pyosmium. How should this be handled?

**Comment by lonvia** [comment]
You can't currently set that with pyosmium. We'd need to expose osmium::io::File and the writer constructor that takes such a File object.
