### ISSUE TITLE
Cannot create geometry

### ISSUE THREAD

**Issue by nikolatr** [osmcode/pyosmium#135]
Hi,

Could you please help me resolve the following error when trying to extract Node geometry? It is interesting that the expected type is osmium.osm.**_osm**.Node.

Traceback (most recent call last):
  File "/workspaces/Nearby/ExtractDataOSM/extract.py", line 32, in <module>
    h.apply_file(input_path, locations=True, idx='flex_mem')
  File "/workspaces/Nearby/ExtractDataOSM/handlers.py", line 65, in node
    self.create_extraction(n)
  File "/workspaces/Nearby/ExtractDataOSM/handlers.py", line 57, in create_extraction
    extraction = ExtractedData(osm_object, self.wkt_factory)
  File "/workspaces/Nearby/ExtractDataOSM/extracted_data.py", line 10, in __init__
    self.set_location(osm_object, wkt_factory)
  File "/workspaces/Nearby/ExtractDataOSM/extracted_data.py", line 24, in set_location
    test = wkt_factory.create_point(node=osm_object)
TypeError: create_point(): incompatible function arguments. The following argument types are supported:
    1. (self: osmium.geom.WKTFactory, location: osmium.osm._osm.Location) -> str
    2. (self: osmium.geom.WKTFactory, node: osmium.osm._osm.Node) -> str
    3. (self: osmium.geom.WKTFactory, ref: osmium.osm._osm.NodeRef) -> str

Invoked with: kwargs: node=Node(id=417543508, deleted=False, visible=True, version=4, changeset=0, uid=0, timestamp=datetime.datetime(2012, 4, 21, 12, 41, 21, tzinfo=datetime.timezone.utc), user='', tags=osmium.osm.TagList({'name'='Јован Јовановић Змај','amenity'='school','name:sr'='Јован Јовановић Змај','name:sr-Latn'='Jovan Jovanović Zmaj'}), location=osmium.osm.Location(x=223211899, y=441126803))

Thanks,
Nikola

**Comment by joto** [comment]
Can you post the program that triggers this error?

**Comment by nikolatr** [comment]
Here is the simple version. It is run inside Ubuntu docker container.

```
import osmium

class SchoolHandler(osmium.SimpleHandler):
    def __init__(self):
        super().__init__()
        self.wkt_factory = osmium.geom.WKTFactory

    def node(self, osm_object):
        if osm_object.tags.get('amenity') == 'school':
            geometry = self.wkt_factory.create_point(node=osm_object)
            print(geometry)

if __name__ == '__main__':
    input_path = 'input_data/serbia-latest.osm.pbf'
    h = SchoolHandler()
    h.apply_file(input_path, locations=True, idx='flex_mem')
```


Traceback (most recent call last):
  File "simple.py", line 16, in <module>
    h.apply_file(input_path, locations=True, idx='flex_mem')
  File "simple.py", line 10, in node
    geometry = self.wkt_factory.create_point(node=osm_object)
TypeError: create_point(): incompatible function arguments. The following argument types are supported:
    1. (self: osmium.geom.WKTFactory, location: osmium.osm._osm.Location) -> str
    2. (self: osmium.geom.WKTFactory, node: osmium.osm._osm.Node) -> str
    3. (self: osmium.geom.WKTFactory, ref: osmium.osm._osm.NodeRef) -> str

Invoked with: kwargs: node=Node(id=417543508, deleted=False, visible=True, version=4, changeset=0, uid=0, timestamp=datetime.datetime(2012, 4, 21, 12, 41, 21, tzinfo=datetime.timezone.utc), user='', tags=osmium.osm.TagList({'name'='Јован Јовановић Змај','amenity'='school','name:sr'='Јован Јовановић Змај','name:sr-Latn'='Jovan Jovanović Zmaj'}), location=osmium.osm.Location(x=223211899, y=441126803))

**Comment by nikolatr** [comment]
Sorry, I am an idiot. I had to put brackets in osmium.geom.WKTFactory**()**
