### ISSUE TITLE
Support python3.8 on Windows

### ISSUE THREAD

**Issue by shotoyoo** [osmcode/pyosmium#136]
Do you support v2.15.4 python3.8 on Windows 10?
 
There seems to be no wheel for v2.15.4, python3.8 for windows
https://pypi.org/project/osmium/#files

Actually, I managed to build osmium from source on Windows10 but it occurs error when import
> import osmium
>  File "C:\cygwin64\home\toyooka\work\trunk\venv\V3-64\debug\Lib\site-packages\osmium\__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: DLL load failed while importing _osmium

If you are planning to provide windows support, that would be great help.
Thanks,

**Comment by lonvia** [comment]
It needs a newer version of Visual Studio but it looks like we can build it with appveyor. Give it a try: https://ci.appveyor.com/api/buildjobs/uhfocqgecif5mw02/artifacts/dist%2Fosmium-2.15.4-cp38-cp38-win_amd64.whl

**Comment by shotoyoo** [comment]
That works ! Thank you for answer :)
