### ISSUE TITLE
simplehandler history problems

### ISSUE THREAD

**Issue by cmikovits** [osmcode/pyosmium#138]
Hello.

I'm trying read a history file.

While processing nodes works very fine to get a timeline, it is not possible with ways, relations or area:

`RuntimeError: Way ID twice in input. Maybe you are using a history or change file?`

Is there any way around this?

**Comment by lonvia** [comment]
You can read history files only when you do not assemble geometry. That means no area callbacks, no geometries for ways.

**Comment by cmikovits** [comment]
Ok. thanks for the quick answer.

Do you know of any way around this problem? E.g. retrieving way IDs only including versions and then further retrieving the area separately based on iD? Is this only possible with separated osm files? One with history, the other one without?

**Comment by joto** [comment]
@cmikovits This is all very vague. If you explain what it is that you are trying to achieve in the end, it might be easier for other to help you.

**Comment by cmikovits** [comment]
Hey, My task is as follows:

1) get all OSM buildings of an area
2) calculate the area of each building
3) get the date of first entry to OSM (version 1) of each building

For small areas I can do it online via the API, this is already working, but it would be really fantastic if this is achievable with the full history planet file.

**Comment by joto** [comment]
You have to do this in two steps. One is the area calculation with a current planet file and one is getting at version 1 using the history file.

**Comment by cmikovits** [comment]
Thanks very much. This clarifies that my current approach is already in the right direction, I just have to change the API call and use the history file instead. Maybe a short question to this topic? Is it possible with simplehandler to fetch a single ID (or a list of IDs)? I know this is possible from the command line, but not sure about the python handling.

**Comment by lonvia** [comment]
No. You can only scan sequentially, which is rather slow to do in Python for finding a single object. You are better off with the command line tools.
