### ISSUE TITLE
uid not showing up in exported features

### ISSUE THREAD

**Issue by l-r** [osmcode/pyosmium#140]
I was testing osmium (`3.0.0`) objects and had 2 questions about this case:

```python
import osmium

fields = osmium.osm.mutable.OSMObject(
    id=123, version=2, visible=True, uid=123, changeset=3212312, timestamp="2015-03-16T04:45:49Z", tags={"maxspeed": "50"}
)

way = osmium.osm.mutable.Way(fields, [])
writer = osmium.SimpleWriter('./output.pbf')
writer.add_way(way)
writer.close()
```

Converting the PBF file back into OPL yields
```xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmconvert 0.8.10">
	<way id="123" version="2" timestamp="2015-03-16T04:45:49Z" changeset="3212312">
		<tag k="maxspeed" v="50"/>
	</way>
</osm>
```

- Why is the `uid` not showing up in the way feature?
- [The constructor for mutable objects](https://github.com/osmcode/pyosmium/blob/master/src/osmium/osm/mutable.py#L12-L13) doesn't take the `user`, is that because this can be changed easily (but uid doesn't)? Is there a way to get the `user` passed in the OSMObject? (I did notice it exists in the `osmium.osm.OSMObject`)

**Comment by lonvia** [comment]
How do you convert PBF to XML? Using `osmium cat` I get:

```
me@machine:/tmp$ osmium cat -f xml output.pbf 
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.10.0">
  <way id="123" version="2" timestamp="2015-03-16T04:45:49Z" uid="123" changeset="3212312">
    <tag k="maxspeed" v="50"/>
  </way>

</osm>
```

The missing `user` attribute is likely just an oversight.

**Comment by lonvia** [comment]
I've added the missing user attribute in fb9d4b2fc6d2a843c9554adb8a878279ddeb2ec5.

**Comment by l-r** [comment]
> How do you convert PBF to XML? Using osmium cat I get:

Ah I see, I had used `osmconvert output.pbf -o=out.osm`

> I've added the missing user attribute in fb9d4b2.

Thank you!

**Comment by l-r** [comment]
@lonvia what is the release process after a small fix like this?

**Comment by lonvia** [comment]
I have planned to do a release in the next days anyway. It will contain the fix.
