### ISSUE TITLE
test_location_tuple fails (AssertionError: 'n0 v0 dV c0 t i0 u T x1 y2' != 'n0 v0 dV c0 t i0 u T x1.0000000 y2.0000000')

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#15]
As reported by Santiago Vila in [Debian Bug #828979](https://bugs.debian.org/828979):
> Dear maintainer:
> 
> This package currently fails to build in stretch:
> 
> ```
> [...]
> FAIL: test_location_tuple (test_writer.TestWriteNode)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/build/pyosmium-2.7.1/test/test_writer.py", line 112, in test_location_tuple
>     w.add_node(O(location=(1, 2)))
>   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/build/pyosmium-2.7.1/test/test_writer.py", line 35, in WriteExpect
>     assert_equals(line, expected)
> AssertionError: 'n0 v0 dV c0 t i0 u T x1 y2' != 'n0 v0 dV c0 t i0 u T x1.0000000 y2.0000000'
> ```
> 
> A full build log is available here:
> 
> https://tests.reproducible-builds.org/debian/rbuild/testing/amd64/pyosmium_2.7.1-2.rbuild.log
> 
> Thanks.

Several of the pyosmium dependencies have been changed in the mean time, but I suspect changes in Python 2.7.12-rc1 are the cause of this issue (Python 2.7.11 was used before).

**Comment by sebastic** [comment]
The change in #16 fixes the test failure on Debian stable & unstable, I'm not entirely sure if it's the appropriate fix for this issue though.

**Comment by lonvia** [comment]
The OPL output format for coordinates has changed in libosmium 2.7.2. It is used in that particular test to check the writer output. I see if I can modify the test so that runs okay against all 2.7.x versions of libosmium.
