### ISSUE TITLE
PyOSMIUM Add Location to way from Node Reference

### ISSUE THREAD

**Issue by ljacobo** [osmcode/pyosmium#156]
I am working with a .osm file and I figured that some places are detailed by the way object without the location but have reference to a node id.

It's possible to get the lat and Lon, from the node that is being referenced?

Thanks.

**Comment by lonvia** [comment]
You  need to add `locations=true` in `apply_file()`, see [the manual](https://docs.osmcode.org/pyosmium/v3.1.0/intro.html#handling-geometries) for more information. You can also use the `area()` callback if you need to assmeble polygons from ways or multipoygon relations.

**Comment by ljacobo** [comment]
Hi Sarah,

I have this file:

```
import osmium as o
import pandas as pd

class ShopListHandler(o.SimpleHandler):

    def __init__(self):
        o.SimpleHandler.__init__(self)
        self.osm_data = []

    def print_shop(self, tags, lon, lat):
        name = tags.get('name', '')
        #print("%f %f %-15s %s" % (lon, lat, tags['amenity'], name))
        for tag in tags:
            self.osm_data.append([lon, lat, tags['amenity'], name])
        #print(self.osm_data)

    def node(self, n):
        if 'amenity' in n.tags:
            self.print_shop(n.tags, n.location.lon, n.location.lat)

h = ShopListHandler()
h.apply_file("sd1.osm", locations=True)

data_colnames = ['lat', 'lon', 'businessType', 'business']
df_osm = pd.DataFrame(h.osm_data, columns=data_colnames)

df_osm.drop_duplicates(subset = "business", keep = "first", inplace = True )

df_osm.to_csv('sd1.csv')
```

And I tried to add a definition to handle the way object in the same way with the nodes but give an error:

`AttributeError: 'osmium.osm._osm.Way' object has no attribute 'location'`.

I know If I do it with  def tag_inventory(self, elem) I can call the elem.location, but, it will relate the <nd ref>  of the way with the node id to take the lat and Lon?

Thanks.

**Comment by lonvia** [comment]
A way itself has no single location. It has an array of nodes which in turn have the location information. So you have to do something like `way.nodes[0].location`.
