### ISSUE TITLE
Basic Example Crashes: RuntimeError: Node callback keeps reference to OSM object. This is not allowed.

### ISSUE THREAD

**Issue by trdavidson** [osmcode/pyosmium#164]
Hi there, trying to run the basic example crashes:

```
import osmium

class CounterHandler(osmium.SimpleHandler):
    def __init__(self):
        osmium.SimpleHandler.__init__(self)
        self.num_nodes = 0

    def node(self, n):
        self.num_nodes += 1
        
osmhandler = CounterHandler()
osmhandler.apply_file('some-file-from-http://download.geofabrik.de/europe.html')
```

with:
```
RuntimeError: Node callback keeps reference to OSM object. This is not allowed.
```

system:
```
python= 3.8
OS= macOS, version 10.15.7 
pyosmium = latest
```

**Comment by lonvia** [comment]
The script works fine for me on Linux, so likely some MacOS issue. How did you install pyosmium?

**Comment by trdavidson** [comment]
Hi @lonvia - apologies for the belated response. The package was installed using `pip`. However, it looks like it's a problem isolated to a `jupyter notebook` environment, as the problem does not occurs when used in a script - as such, we can close this issue.

**Comment by lonvia** [comment]
I quickly tried with my jupyter installation and it works there for me, too. I wonder if there is a particular combination of installed packages that causes trouble. If you can figure out steps to reproduce the jupyter setup that exposes the problem, feel free to reopen.
