### ISSUE TITLE
Are Prerequisites Libraries needed for building or also running ?

### ISSUE THREAD

**Issue by di-rect** [osmcode/pyosmium#168]
Hello,

I was wondering if the Prerequisites Libraries are needed for building only or need to be kept for running, so need to be `"make install"`-ed

That's all :)

Thanks!

**Comment by joto** [comment]
You can use the same command as in here: https://github.com/osmcode/osmium-tool/issues/208

**Comment by di-rect** [comment]
Yes I was doing that but the following question was, does everything in contrib needs to be compiled in front of psyosmium install ?
