### ISSUE TITLE
Add pyosmium to PyPi

### ISSUE THREAD

**Issue by pnorman** [osmcode/pyosmium#17]
The [osmium](https://pypi.org/project/osmium/) listed on pypi is for the old osmium, not the new libosmium. It would be useful to be able to install pyosmium via pip without specifying a git repo

**Comment by joto** [comment]
It looks like this was packaged by @jokoala. Can you comment?

**Comment by jokoala** [comment]
Hi, sorry that I'm answering so late. It is true, I tried a packaging of the osmium library some years ago. Since I did not maintain this port, I suggest that I handover the ownership for the "osmium" PyPI package to you. Can you send me an account name on PyPI, which I should register as "owner"?

**Comment by lonvia** [comment]
@jokoala I'm the principle maintainer of this repo and would also take on the packaging. I've just registered a user 'lonvia' with pypi. If you can transfer ownership to this user that would be great.

**Comment by jokoala** [comment]
Done, didn't want to block the name. Once you have access, feel free to remove the "Owner" role from my account. Again please excuse if I've caused confusion in the OSM world...

**Comment by joto** [comment]
Thanks @jokoala !

**Comment by lonvia** [comment]
The 2.9.0 version of pyosmium is now available via Pypi.

Thanks a lot @jokoala, that was easy. Also thanks for packaging the previous version.
