### ISSUE TITLE
Quickly gather lat/lon data from node number

### ISSUE THREAD

**Issue by DarylRob** [osmcode/pyosmium#177]
Is it possible to pull lat/lon for a given node

**Comment by lonvia** [comment]
Do you want the position of a node within the node callback or at a later time? Maybe you can given an example on what exactly you are trying to achieve?

**Comment by DarylRob** [comment]
Hi Sarah,

**Comment by DarylRob** [comment]
Hi Sarah
Sorry I'm a bit of a novice at anything programming still.

So currently I have a list of nodes along a route for around 66,000 routes and I want to find the latitude and longitude for each of these nodes, which will then be used to lookup if a postcode is within x miles of a node. 
 
I was using the openstreetmaps API to lookup a node to find these but it's not possible with 66,000 routes each with 1000+ nodes.

**Comment by lonvia** [comment]
So you start with a simple list of OSM node IDs and want their positions? That is fairly easy.

If you have the complete list to start with, write a simple handler that processes nodes and collect the lat/lon in the callback there. Something along the lines of [this example](https://github.com/osmcode/pyosmium/blob/7d84cc4cfd3ccf44818840fe8e59258e6bfd3de7/examples/amenity_list.py#L22).

If you want to be able to look up lat/lon of a random node ID (e.g you want to process your routes in order they come in), then you should convert an OSM file to a persistent node cache first. You can then reopen this node cache later and look up random positions for nodes. You can use [create_nodecache.py](https://github.com/osmcode/pyosmium/blob/master/examples/create_nodecache.py) to create the nodecache file and look at [use_nodecache.py](https://github.com/osmcode/pyosmium/blob/master/examples/use_nodecache.py) for using it.

**Comment by DarylRob** [comment]
I really appreciate your help on this, but it seems I'm not very technical when it comes to these things. 

in the create_nodecache.py where am I specifying the .osm.pbf file ?

**Comment by lonvia** [comment]
See [usage](https://github.com/osmcode/pyosmium/blob/7d84cc4cfd3ccf44818840fe8e59258e6bfd3de7/examples/create_nodecache.py#L5). The filename needs to be supplied as the second command line parameter and is used in https://github.com/osmcode/pyosmium/blob/7d84cc4cfd3ccf44818840fe8e59258e6bfd3de7/examples/create_nodecache.py#L10
