### ISSUE TITLE
pyosmium-get-changes - No error when buffer size is exceeded

### ISSUE THREAD

**Issue by FaFre** [osmcode/pyosmium#178]
It took me a while right now to figure out why my downloaded changes were incomplete.

Only after turning on full debug mode I found out about the negative buffer size. There was no error reported and the script returned with exit code 0. This is not a good behavior - especially when working with automated scripts. 

The default value for size is with 100MB very low when the user is working with daily change-sets, maybe this value should be upped a bit for convenience?

I worked with the current pyosmium 3.1.3.

**Comment by lonvia** [comment]
Yeah, pyosmium-get-changes is meant to be run in a loop until you get an error status of 3 (meaning: no more data available).
