### ISSUE TITLE
Repeated updates lead to osm.pbf files that are missing nodes in ways

### ISSUE THREAD

**Issue by leonardehrenfried** [osmcode/pyosmium#181]
I'm updating an OSM extract provided by Geofabrik every night and from the updated file I generate map tiles. Usually this works without a hitch but tonight `py-osmium-up-to-date` produced a file where nodes are missing from ways. I have saved the file from before the update and here are the reproduction steps to produce the inconsistent files.

```
wget https://leonard.io/stadtnavi/germany-failing-to-update.osm.pbf
2021-08-09 09:44:59 (109 MB/s) - ‘germany-failing-to-update.osm.pbf’ saved [3672571555/3672571555]
```
```
osmium --version
osmium version 1.13.1
libosmium version 2.16.0
Supported PBF compression types: none zlib lz4
```
```
osmium check-refs germany-failing-to-update.osm.pbf 
[======================================================================] 100% 
There are 346521955 nodes, 56588796 ways, and 702051 relations in this file.
Nodes in ways missing: 0
```
Here you can see that the file is consistent and no nodes are missing from the ways.

```
pyosmium-up-to-date --version
pyosmium 3.1.3
```
```
pyosmium-up-to-date germany-failing-to-update.osm.pbf 
```
```
osmium check-refs germany-failing-to-update.osm.pbf 
[======================================================================] 100% 
There are 346605856 nodes, 56602801 ways, and 702342 relations in this file.
Nodes in ways missing: 16
```
However, when you update the file with `py-osmium-up-to-date` this produces a file with 16 missing nodes.

This causes my downstream process (`tilemaker`) to fail.

Is this a problem with `py-osmium-up-to-date`?

If it matters: this is Debian 10 with the packages installed from the backports repo.

**Comment by leonardehrenfried** [comment]
@simonpoole has asked for the log with `-i`. Here it is:

```
osmium check-refs -i germany-failing-to-update.osm.pbf 
n8196246004 in w881250502===========================================>  ]  97% 
n8196246003 in w881250502
n8196246002 in w881250502
n8196246001 in w881250502
n8196246000 in w881250502
n8196245999 in w881250502
n8196245998 in w881250502
n8196245997 in w881250502
n8196245996 in w881250502
n8196245994 in w881250502
n8196245993 in w881250502
n8196245992 in w881250502
n8196245991 in w881250502
n8196245989 in w881250502
n8196245988 in w881250502
n8196246004 in w881250502
[======================================================================] 100% 
There are 346605856 nodes, 56602801 ways, and 702342 relations in this file.
Nodes in ways missing: 16
```

**Comment by lonvia** [comment]
@leonardehrenfried Can you test the latest version from master and see if that really fixes things for you?

**Comment by leonardehrenfried** [comment]
OK, will do but since I need to spin a VM and install the deps this will take a little while.

**Comment by leonardehrenfried** [comment]
That's fine by me. I will be the first to test once it hits the Debian repos. 

Thanks for the quick fix!
