### ISSUE TITLE
Help implementing recursion

### ISSUE THREAD

**Issue by fsalerno-sdc** [osmcode/pyosmium#183]
I'm using PyOsmium to fetch data on a global scale, specifically all `boundary=administrative` with `admin_level=4` regions with their names in several languages and, crucially, the country they belong to.

However, this last information is not available on either the relation or label node of the region itself, and unless there's some better way I missed, this means I need to get it by recursing up to look at all relations of `admin_level=2` to find one that has the region as a member.

The Overpass API allows recursion out of the box, however I think PyOsmium does not allow this (or at least has no convenient interface for it), and I can't seem to make Overpass work for my purposes: as I need data for the whole globe, it always times out.

I will look into ways to do what I need with Overpass (e.g. joining together various bounding boxes I can query separately), but in the meantime I'd like to know what would be the smartest way to recurse up using PyOsmium, given a certain node or relation. I already have a working PyOsmium script and if possible I'd like to expand it for my purposes rather than make a whole new one to use Overpass.

**Comment by lonvia** [comment]
This is a issue tracker for the pyosmium library not a general discussion forum about OSM data processing. A much better place to discuss general data questions is on https://help.openstreetmap.org

That said, to figure out what boundary a country belongs to, you need to extract the countries, the level 4 boundaries and establish a geometric relationship.
