### ISSUE TITLE
I am unable to install osmium using pip

### ISSUE THREAD

**Issue by ritchiebd2** [osmcode/pyosmium#186]
Here is the output when I do pip install osmium

PS C:\Users\benri\Documents\Class\Capstone\Repo\Capstone> pip install osmium
Collecting osmium
  Using cached osmium-3.2.0.tar.gz (2.3 MB)
Requirement already satisfied: requests in c:\users\benri\appdata\roaming\python\python39\site-packages (from osmium) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\benri\appdata\roaming\python\python39\site-packages (from requests->osmium) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\benri\appdata\roaming\python\python39\site-packages (from requests->osmium) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\benri\appdata\roaming\python\python39\site-packages (from requests->osmium) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\benri\appdata\roaming\python\python39\site-packages (from requests->osmium) (3.0.4)
Building wheels for collected packages: osmium
  Building wheel for osmium (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\benri\anaconda3\envs\Capstone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install
-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\setup.py'"'"'; __file__='"'"'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\
\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\benri\AppData\Local\Temp\pip-wheel-laogk684'
       cwd: C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\
  Complete output (65 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\osmium
  copying src\osmium\helper.py -> build\lib.win-amd64-3.9\osmium
  copying src\osmium\version.py -> build\lib.win-amd64-3.9\osmium
  copying src\osmium\__init__.py -> build\lib.win-amd64-3.9\osmium
  creating build\lib.win-amd64-3.9\osmium\osm
  copying src\osmium/osm\mutable.py -> build\lib.win-amd64-3.9\osmium/osm
  copying src\osmium/osm\__init__.py -> build\lib.win-amd64-3.9\osmium/osm
  creating build\lib.win-amd64-3.9\osmium\replication
  copying src\osmium/replication\server.py -> build\lib.win-amd64-3.9\osmium/replication
  copying src\osmium/replication\utils.py -> build\lib.win-amd64-3.9\osmium/replication
  copying src\osmium/replication\__init__.py -> build\lib.win-amd64-3.9\osmium/replication
  running build_ext
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:2 (project):
    Generator
  
      NMake Makefiles
  
    does not support platform specification, but platform
  
      x64
  
    was specified.
  
  
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/benri/AppData/Local/Temp/pip-install-u1bbvlao/osmium_0030fd7ae1984bd2889b208ed260cbb6/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 124, in <module>
      setup(
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\benri\AppData\Roaming\Python\Python39\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 67, in run
      self.build_extension(ext)
    File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 113, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "C:\Users\benri\anaconda3\envs\Capstone\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6', '-DCMAKE_LIBRARY_OUTPUT_DI
RECTORY=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\benri\\anacon
da3\\envs\\Capstone\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\buil
d\\lib.win-amd64-3.9', '-A', 'x64', '-DOSMIUM_INCLUDE_DIR=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/libosmium/inclu
de', '-DPROTOZERO_INCLUDE_DIR=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/protozero/include', '-DPYBIND11_PREFIX=C:\\
Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/pybind11']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for osmium
  Running setup.py clean for osmium
Failed to build osmium
Installing collected packages: osmium
    Running setup.py install for osmium ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\benri\anaconda3\envs\Capstone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-insta
ll-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\setup.py'"'"'; __file__='"'"'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb
6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().re
place('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\benri\AppData\Local\Temp\pip-record-344ap1c5\install-record.txt
' --single-version-externally-managed --compile --install-headers 'C:\Users\benri\anaconda3\envs\Capstone\Include\osmium'
         cwd: C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\
    Complete output (67 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\osmium
    copying src\osmium\helper.py -> build\lib.win-amd64-3.9\osmium
    copying src\osmium\version.py -> build\lib.win-amd64-3.9\osmium
    copying src\osmium\__init__.py -> build\lib.win-amd64-3.9\osmium
    creating build\lib.win-amd64-3.9\osmium\osm
    copying src\osmium/osm\mutable.py -> build\lib.win-amd64-3.9\osmium/osm
    copying src\osmium/osm\__init__.py -> build\lib.win-amd64-3.9\osmium/osm
    creating build\lib.win-amd64-3.9\osmium\replication
    copying src\osmium/replication\server.py -> build\lib.win-amd64-3.9\osmium/replication
    copying src\osmium/replication\utils.py -> build\lib.win-amd64-3.9\osmium/replication
    copying src\osmium/replication\__init__.py -> build\lib.win-amd64-3.9\osmium/replication
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:2 (project):
      Generator
    
        NMake Makefiles
    
      does not support platform specification, but platform
    
        x64
    
      was specified.
    
    
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/benri/AppData/Local/Temp/pip-install-u1bbvlao/osmium_0030fd7ae1984bd2889b208ed260cbb6/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 124, in <module>
        setup(
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 67, in run
        self.build_extension(ext)
      File "C:\Users\benri\AppData\Local\Temp\pip-install-u1bbvlao\osmium_0030fd7ae1984bd2889b208ed260cbb6\setup.py", line 113, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\Users\benri\anaconda3\envs\Capstone\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6', '-DCMAKE_LIBRARY_OUTPUT_
DIRECTORY=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\benri\\anac
onda3\\envs\\Capstone\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\bu
ild\\lib.win-amd64-3.9', '-A', 'x64', '-DOSMIUM_INCLUDE_DIR=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/libosmium/inc
lude', '-DPROTOZERO_INCLUDE_DIR=C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/protozero/include', '-DPYBIND11_PREFIX=C:
\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6/contrib/pybind11']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\benri\anaconda3\envs\Capstone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\benri
\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmium_0030fd7ae1984bd2889b208ed260cbb6\\setup.py'"'"'; __file__='"'"'C:\\Users\\benri\\AppData\\Local\\Temp\\pip-install-u1bbvlao\\osmiu
m_0030fd7ae1984bd2889b208ed260cbb6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup;
 setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\benri\AppData\Local\Temp\pip-r
ecord-344ap1c5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\benri\anaconda3\envs\Capstone\Include\osmium' Check the logs for full comm
and output.

**Comment by lonvia** [comment]
Please make sure, you have all prerequisites mentioned in the [README](https://github.com/osmcode/pyosmium#prerequisites), in particular CMake. We build on our CI using Miniconda, so building on anaconda should woke fine as well. You can have a look at the [CI script](https://github.com/osmcode/pyosmium/blob/633a3d95348678544db4d968d20c6718dbeb3390/appveyor.yml) for hints on installing prerequisits. Further than that, we can't unfortunately give installation support for Windows, as none of the maintainers has a Windows machine at their disposal.
