### ISSUE TITLE
Search on bbox (or gps coordinates)

### ISSUE THREAD

**Issue by jugurthab** [osmcode/pyosmium#188]
Hi,

I would like to know if there is a way to limit the search on a particular bbox (or even a single gps coordinates).

For example, how to list the tags (highway, cycle, ...etc) for the current user position? 

I need to complete the code to search only for a specific bbox (or a single coordinate):
osm_super_file = osm.io.Reader(self.osm_path, osm.osm.osm_entity_bits.WAY)
osm.apply(osm_super_file, simpleHandler())

Is there any solution?

Thanks

**Comment by lonvia** [comment]
pyosmium is a low-level library to read OSM data files in a streaming fashion. If you want to search through OSM data, you need some higher level application or a database. This is not the right place to discuss such solutions. Try https://help.openstreetmap.org.

**Comment by cefect** [comment]
I also think this would be a useful feature
