### ISSUE TITLE
Relation member list should accept RelationMembers in SimpleWriter

### ISSUE THREAD

**Issue by RakeshGupta-tomtom** [osmcode/pyosmium#194]
I have scenario like 
I have relation which have some members
now I want to remove some of the member from it and writing back relation to file 
 relation(self, relation):
                ref_mem= []       
                  for member in relation.members:                              
                if member.type == 'r' :
                   logging.info("r member found")
                else:
                    ref_mem.append(member) 
  // Here I want something like relation.member.replace(ref_mem)                 
            self.writer.add_relation(relation)

**Comment by lonvia** [comment]
You need to create a [mutable OSM object](https://docs.osmcode.org/pyosmium/latest/ref_osm.html#mutable-osm-objects) with your custom member list. You can simply use the replace function for that:

```
    self.writer.add_relation(relation.replace(members=ref_mem))
```

See [writing OSM data](https://docs.osmcode.org/pyosmium/latest/intro.html#writing-osm-data) for more infirmation.

**Comment by RakeshGupta-tomtom** [comment]
when i try to do  self.writer.add_relation(relation.replace(members=ref_mem))
then its says RelationListMember not iteratable

**Comment by lonvia** [comment]
Can you please provide a full code example that allows to reproduce the problem here?

**Comment by RakeshGupta-tomtom** [comment]
This is what I wrote in call back method  

def relation(self, relation):      
        without_ref_members = []       
        if relation.id not in self.relation_ids:
            for member in relation.members:                                             
                if member.type == 'r' and  member.ref in self.relation_ids:
                   logging.info("found referential integrity")
                   without_ref_members.append(member) 
            self.writer.add_relation(relation.replace(members=without_ref_members) )

Here what I want is in relation object I want to replace without_ref_members in relation.member

'osmium.osm._osm.RelationMember' object is not iterable
  File "/home/rakesh/python-project/open-maps-osm-area-filter/osm_area_filter/osm_handler.py", line 44, in relation
    self.writer.add_relation(relation.replace(members=without_ref_members) )

**Comment by lonvia** [comment]
I mean a _complete_ script. Something that I can directly execute without having to spend lots of time writing the boiler plate code around.

**Comment by RakeshGupta-tomtom** [comment]
import argparse
import logging
import os.path


from osm_handler import AdminAreaHandler
from wkt_handler import WktHandler
from ids_handler import IdsHandler
from postal_Ids_handler import PostalIdsHandler
from postal_handler import PostalAreaHandler
import shapely.wkt
from shapely.ops import unary_union
from shapely.geometry import shape
import geojson


def main():
    logging.basicConfig(level=logging.INFO)
    execute()



def filter_command(args):
    if os.path.exists(args.output):
        logging.warning("Output file exists, skipping...")
        return

    logging.info("Filtering the ids out of the pbf")
    handler = AdminAreaHandler(args.output)
    handler.apply_file(args.input.name)

def execute():
    parser = argparse.ArgumentParser()
    subs = parser.add_subparsers()

    filter_comm = subs.add_parser('filter', help='Command for filtering out admin areas ')
    filter_comm.add_argument('-i', '--input', type=argparse.FileType('r'), help='The input PBF file', required=True)
    filter_comm.add_argument('-b', '--border', type=argparse.FileType('r'), help='The input border WKT file',required=True)
    filter_comm.add_argument('-o', '--output', type=str, help='The output PBF file', required=True)
    filter_comm.add_argument('--filterCityCenters', dest='filter_city_centers', default=False, action='store_true',help='Filter osm City Center nodes')
    filter_comm.set_defaults(func=filter_command)

    args = parser.parse_args()
    if 'func' in args:
        args.func(args)


if __name__ == "__main__":
        main()

**Comment by RakeshGupta-tomtom** [comment]
from ensurepip import version
import logging
from weakref import ref
from osmium import SimpleHandler, SimpleWriter
from osmium.osm import _list_repr,_list_elipse
from tag_filters import *
import osmium.osm as o


class AdminAreaHandler(SimpleHandler):
    def __init__(self, output_file):
        SimpleHandler.__init__(self)
        self.writer = SimpleWriter(output_file)
   
    def relation(self, relation):      
        without_ref_members = []       
        for member in relation.members:                                             
            if member.type == 'r':
               logging.info("found referential integrity")
               without_ref_members.append(member) 
        self.writer.add_relation(relation.replace(members=without_ref_members) )

**Comment by RakeshGupta-tomtom** [comment]
Hi shared both files

**Comment by RakeshGupta-tomtom** [comment]
Hi Lonvia,
I guess issue is RelationMemberList is an object which have RelationMembers as on arrayObjects,
 RelationMemberList object , not able to instantiate object . since constructor is not available
Do you know how to create object of RelationMemberList with assigning RelationMember

**Comment by lonvia** [comment]
Ah, adding RelationMembers directly is not implemented at the moment. Please use:

```
without_ref_members.append((member.type, member.ref, member.role))
```

I've changed the title to reflect the issue. This is definitely something that needs implementing. Please leave the issue open.

**Comment by RakeshGupta-tomtom** [comment]
Thanks Sarah , for now error is gone but Members are not replaced , still its keeping the old one

**Comment by lonvia** [comment]
This must be an error in your script. It works fine here. In any case, it would be a different issue. If you believe that it really is an issue with pyosmium, open an new issue and provide a reproducible case (please note that your script above still wasn't executing without removing tons of code).

**Comment by RakeshGupta-tomtom** [comment]
Thanks Sarah for quick support , appreciated , it works now .
And apologize for the script code ,yeah that was raw script
