### ISSUE TITLE
SimpleWriter truncates float digits on location

### ISSUE THREAD

**Issue by jmaiolini** [osmcode/pyosmium#201]
Hello everyone.
I'm facing an issue with the SimpleWriter. I need to have at least 12 decimal precision on locations for nodes but when the file is written, it loses precision up to 7 digits.

    import osmium as o
    
    writer = o.SimpleWriter(str(osm_filepath))

    node1 = o.osm.mutable.Node(id=1, location=(10.312076299336217,44.762644057253354))
    writer.add_node(node1)

    node2 = o.osm.mutable.Node(id=2, location=(float(10.312076299336217),float(44.762644057253354)))
    writer.add_node(node2)
    
    node3 = o.osm.mutable.Node(id=3)
    node3.location = (float(10.312076299336217), float(44.762644057253354))
    
    writer.add_node(node3)

Output:

    <?xml version='1.0' encoding='UTF-8'?>
    <osm version="0.6" generator="libosmium/2.18.0">
      <node id="1" lat="44.7626441" lon="10.3120763"/>
      <node id="2" lat="44.7626441" lon="10.3120763"/>
      <node id="3" lat="44.7626441" lon="10.3120763"/>
    </osm>

I've seen in issue #83 that the cast with my current version is indeed on double, so I don't know why the location is currently being truncated, maybe I am missing something very trivial.

Thank you in advance.

-----

OS: Ubuntu 20.04
Python: 3.8
Osmium version: 3.3.0 (installed with pip)

**Comment by joto** [comment]
OSM only has a precision of 7 digits, so this is correct. (Coordinates are stored internally as 32bit integers.)
