### ISSUE TITLE
Storing a list of lon-lat-coordinates

### ISSUE THREAD

**Issue by corni3011** [osmcode/pyosmium#203]
I want to use pyosmium to get the coordinates of all schools in the state that I am living in. So far, I have written this code:
```python
class DataHandler(osmium.SimpleHandler):
     def __init__(self):
          osmium.SimpleHandler.__init__(self)
          self.schools = []

     def node(self, n):
          if n.tags.get('amenity') == 'school' and 'name' in n.tags:
               self.schools.append((n.location.lat, n.location.lon))

h = DataHandler()
h.apply_file(FILE_PATH, locations=True)
print(sorted(h.schools))
```
I have also played around with copy.deepcopy to create deep copies of those coordinates before adding them to the list but I keep running into this error:
```
Node callback keeps reference to OSM object. This is not allowed
```
I know that this error means that I can only store deep copies of those informations but still, I can't figure out how to do so in a way, that doesn't raise this exception.

**Comment by lonvia** [comment]
This was an Ubuntu 22.04?

**Comment by corni3011** [comment]
No, it was an Ubuntu 21.10

**Comment by lonvia** [comment]
I've just tried with a vanilla VM with Ubuntu 21.10 and the script worked fine, too. So it is probably something special in the setup of the VM that caused the error. It would be interesting to get to the root of this but it's probably too difficult to find.
