### ISSUE TITLE
No area for some countries (e.g. Spain)

### ISSUE THREAD

**Issue by BradleyGrantham** [osmcode/pyosmium#204]
I'm using pyosmium to import OpenStreetMap data. Specifically, I would like all the polygons of countries, cities and towns.

I'm using the `area` callback which is working extremely well, however it's missing some countries.
For example, Spain can't be found as an area within either `europe-latest.osm.pbf` or `spain-latest.osm.pbf`

France is another example (although `Metropolitan France` is there)

**Comment by lonvia** [comment]
This is not an issue of pyosmium. It's a problem with your input data.

If you use extracts, then it is not always guaranteed that the country relation is completely contained in the extract. If I have to take a guess for Spain, I'd blame the exclave of Melida which isn't completely contained in the Spain or Europe extracts of Geofabrik.

**Comment by BradleyGrantham** [comment]
Wow. Thank you so much for your response! I really appreciate it. I will try with the full planet extract :)
