### ISSUE TITLE
Could not convert osm to geoJson

### ISSUE THREAD

**Issue by aSeniyants** [osmcode/pyosmium#209]
Hello.
I try:
`python3 convert.py map.osm data.geoJSON`

and get:

`RuntimeError: Could not detect file format for filename 'data.geoJSON'.`

Please. help me. Thank you

**Comment by lonvia** [comment]
`convert.py` is just a simple example that shows how to use the SimpleWriter. It only support OSM data formats as output. geojson is not one of them. Use [osmium export](https://docs.osmcode.org/osmium/latest/osmium-export.html) from the osmium suite for converting to geojson.

**Comment by aSeniyants** [comment]
> 

From my python script use:
`osmium export map.osm -o data.geojson`

yes?

**Comment by joto** [comment]
No, not from Python. It's a command line tool.
