### ISSUE TITLE
Provide pre-filtering by id, tags etc.

### ISSUE THREAD

**Issue by tbicr** [osmcode/pyosmium#218]
in issues already mentioned that there are no plans to add filtering functionality as `osmium tags-filter` or `osmium getid` or `osmium removeid` and etc. provided

most of this logic can be implemented wrapping `osmium` with `subprocesses.run`

however it would be nice to have python bindings to apply filtering logic

**Comment by lonvia** [comment]
There certainly won't be direct 1:1 bindings for the functions provided by osmium-tool but I do have vague ideas to provide fast pre-filtering directly in pyosmium. There are no concrete plans when this will happen.

**Comment by lonvia** [comment]
#244 implements pre-filtering by tags and for objects without tags. Filtering by ID seems rather odd.
