### ISSUE TITLE
Support for Mac ARM binary wheels

### ISSUE THREAD

**Issue by aignas** [osmcode/pyosmium#227]
Hello, is there a possibility to build Mac ARM wheels (or the new format `universal2` wheels) for this platform?

**Comment by lonvia** [comment]
According to [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) it is possible to build but not test the wheels. I won't distribute untested wheels especially not on an architecture that isn't used anywhere else. I'm sorry.

**Comment by cdbattags** [comment]
It looks like this is supported now?

https://cibuildwheel.readthedocs.io/en/stable/options/#test-command

**Comment by lonvia** [comment]
Still not on Github Actions: https://cibuildwheel.readthedocs.io/en/stable/#usage

**Comment by PierreMesure** [comment]
Looks like it is now? (in the table you link to)

**Comment by lonvia** [comment]
Oh, Github runners for MacOS ARM. Nice.

I've built the 2.7.0 version for macos-arm now: https://github.com/lonvia/pyosmium/actions/runs/8582188319

Only available for Python 3.9+. If somebody can try out the wheels in the artifact in the run above ( pyosmium-wheels-macos-14 ) and confirm that they work, I can see how to get them on pypi.org.

**Comment by PierreMesure** [comment]
Wow, thank you for fixing it so fast! I can give them a try.

I've been using pyosmium on Linux and I can't get it to produce the same results as the CLI executable osmium though.

**Comment by hoffmann** [comment]
Thanks for building the wheels. Works nice with python 3.12 on a M1 pro with macOS Ventura 13.4.

**Comment by lonvia** [comment]
Thanks for testing. I've uploaded them to pypi.org now.

Leaving this issue as this still needs integration in the master branch.
