### ISSUE TITLE
Documentation with more examples and more complete examples would be very helpful

### ISSUE THREAD

**Issue by velle** [osmcode/pyosmium#230]
When I read the pyosmium documentation (and in fact also the documentation for osmium and libosmium) I get a feeling that it is written by and for people who already have a lot more insight than I have. It is very brief, there are very few examples, and the examples are not what I would call full examples, they are rather snippets. 

I have a solid background in Python and some background in GIS (mostly QGIS and all the OGR formats), but I am quite new to the technical side of OSM, OSM formats and OSM tools. Even though I am not the least qualified user one could imagine, my experience is that the pyosmium learning curve is extremely steep. And the limited scope and lack of full examples make it much steeper than it needs to be. 

Is it ok if I (and maybe others) write suggestions on which topics/aspects I recommend that you expand your documentation? Is it appreciated? Is it discouraged? Maybe you don't have the resources, and maybe its not a priority? I would not want to write such suggestions if the people developing osmium/pyosmium get the impression that I am spoiled or unappreciative because I keep pointing out issues, while they are making a tool freely available :)

Sincerely

**Comment by joto** [comment]
We are all fully aware that the documentation of these projects isn't great. But, as you mentioned, the resources (time and money) simply are not there. Any help you can provide actually documenting something (or helping with providing funds for this) is appreciated.
