### ISSUE TITLE
Would it be possible to make a new release?

### ISSUE THREAD

**Issue by matkoniecz** [osmcode/pyosmium#250]
I entirely understand that there is no real support for this project (I have seen https://github.com/osmcode/pyosmium/issues/230#issuecomment-1540020994 and I have hunch while [main committer](https://github.com/osmcode/pyosmium/commits/master/) is busy) but I got quite confused when I tried following examples and it kept crashing.

I will open and close it immediately to potentially save someone confusion in future.

original issue text: 

pub_names example is crashing 

```
mateusz@grima:$ python3.10 pub_names.py /media/mateusz/OSM_cache/geofabrik_downloads/europe-poland-malopolskie.osm.pbf
Traceback (most recent call last):
  File "/home/mateusz/Documents/install_moje/OSM_software/shops_lister/shops/pub_names.py", line 21, in <module>
    exit(main(sys.argv[1]))
  File "/home/mateusz/Documents/install_moje/OSM_software/shops_lister/shops/pub_names.py", line 8, in main
    for obj in osmium.FileProcessor(osmfile)\
AttributeError: module 'osmium' has no attribute 'FileProcessor'
```

I checked pip for the same python version:
```
mateusz@grima:$ pip --version
pip 23.3.1 from /home/mateusz/.local/lib/python3.10/site-packages/pip (python 3.10)
```

and checked that I have latest release:

```
mateusz@grima:$ pip list | grep osmium
osmium                    3.7.0
```

Looking at what is in osmium, it appears that FileProcessor is not there:

```
Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osmium
>>> dir(osmium)
['Area', 'BaseHandler', 'Callable', 'Changeset', 'HandlerFunc', 'InvalidLocationError', 'MergeInputReader', 'Node', 'NodeLocationsForWays', 'Optional', 'Relation', 'SimpleHandler', 'SimpleWriter', 'T', 'TypeVar', 'Way', 'WriteHandler', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_osmium', 'apply', 'geom', 'helper', 'index', 'io', 'make_simple_handler', 'osm', 'osmium']
```

Looking at https://github.com/osmcode/pyosmium/commits/b5d78f670d0e2132bbb1647261332702af2ed084/src/osmium/file_processor.py - it seems relatively new...

Looking at https://pypi.org/project/osmium/#history it seems that it is just newer than latest release, so I was trying to use not released code.

Lets go to docs how to build from source, I guess?

**Comment by lonvia** [comment]
The `example` directory is always for the source code it comes with. What you see on github, is part of the master branch. If you work with a release, look at the [example directory of the release](https://github.com/osmcode/pyosmium/tree/v3.7.0/examples).

The master branch is in an intermediate development stage, not ready for a release. Please be aware that you work with unreleased versions at your own peril. The new FileProcessor interface is likely to still change a bit before the next release.
