### ISSUE TITLE
Relations in .osm file are not imported as areas

### ISSUE THREAD

**Issue by luwhite** [osmcode/pyosmium#259]
I'm trying to import OpenStreetMap data of Saarland, downloaded from geofabrik, using pyosmium. However some relations tagged as "boundary administrative", like Landkreis Merzig-Wadern or Losheim am See are not imported as areas. I've checked the .osm file and they are actually present. It looks like that input data are ok: I could not find any formal difference between those relations and others that are instead imported.

**Comment by lonvia** [comment]
The Saarland extract from Geofabrik is incomplete. It is missing the little corner [here](https://www.openstreetmap.org/#map=16/49.5478/6.6539) on the map.

CC @woodpeck

**Comment by woodpeck** [comment]
Thank you lonvia for debugging. I have fixed the extract boundary and with any luck the new extract (due in a few hours) should have the full relation.

**Comment by lonvia** [comment]
Cool. Closing as data issue.
