### ISSUE TITLE
Support for Linux ARM binary wheels

### ISSUE THREAD

**Issue by mojodna** [osmcode/pyosmium#260]
Docker on Apple Silicon Macs, Graviton EC2 instances, Raspberry Pis, etc. run ARM Linux. Linux wheels are only available for x86. Can we expand the build matrix to build wheels for Linux on ARM?

**Comment by mojodna** [comment]
#258 addresses this.

**Comment by lonvia** [comment]
The imminent 4.0 release will have binary wheels for Python >= 3.9.
