### ISSUE TITLE
E: Unable to locate package python3-pytest-httpserver when following install instructions

### ISSUE THREAD

**Issue by matkoniecz** [osmcode/pyosmium#263]
I tried to follow https://github.com/osmcode/pyosmium?tab=readme-ov-file#testing

```
sudo apt-get install python3-pytest python3-pytest-httpserver
```

gives me

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pytest-httpserver
```

```
lsb_release -a                                                                                                                                                  
```

for me is

```
No LSB modules are available.                                                                                                                                                                
Distributor ID: Ubuntu                                                                                                                                                                       
Description:    Ubuntu 20.04.6 LTS                                                                                                                                                           
Release:        20.04
Codename:       focal
```

(XY problem avoidance: I am trying to figure out how to instantiate `osmium.osm.TagList` - `osmium.osm.TagList({'shop': 'supermarket'})` seemingly works but functionality working for real `TagList` breaks, found https://docs.osmcode.org/pyosmium/latest/ref_osm.html#osmium.osm.TagList but I remain confused what needs to be passed as `TagContainerProtocol`, https://github.com/osmcode/pyosmium/blob/master/test/test_taglist.py is my last trace and wanted to step through test with debugger to find out how it instantiates `TagList` as reading code left me confused)

**Comment by ImreSamu** [comment]
>  Unable to locate package python3-pytest-httpserver 

try `pip install pytest pytest-httpserver shapely`
https://github.com/osmcode/pyosmium/blob/df429ca54806bef5bc5f99a30bd7f8ab29413500/.github/actions/run-tests/action.yml#L7C17-L7C60

**Comment by lonvia** [comment]
Ubuntu has this only starting 23.04. I think it is fair to expect a recent OS for development.

NB: TagLists are not instantiatable from Python. Use a simple dict.

**Comment by matkoniecz** [comment]
> Use a simple dict.

the tricky part is that dict has some extra methods, so code was not failing in tests but was failing with real code

and in turn when iterating over TagList you can use `k` `v` on elements that you cannot use on dict elements

I guess I can call `dict(tag_list)` and hope that performace penalty is not too great

> TagLists are not instantiatable from Python

at least I know that I can stop looking for rolution here

**Comment by lonvia** [comment]
Please do not start off-topic discussions on unrelated issues, use the Discussion section.
