### ISSUE TITLE
Add man pages for tools

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#29]
The new `pyosmium-get-changes` & `pyosmium-up-to-date` tools don't have man pages to document them.

Having them be self-documenting like `osmium` would be great.

**Comment by lonvia** [comment]
Sphinx has a [builder for man pages](http://www.sphinx-doc.org/en/stable/config.html#options-for-manual-page-output). The other option is to extend setup.py with a new command, there is some useful code [here](https://github.com/andialbrecht/build_manpage).

**Comment by lonvia** [comment]
I've ended up using the Sphinx builder. `cd doc; make man` now creates a man page from the inline documentation in the tool scripts. Needs sphinx-autoprogram for building.
