### ISSUE TITLE
Python 3.5 import error

### ISSUE THREAD

**Issue by Xevib** [osmcode/pyosmium#33]
I setup a travis to test a library that uses pyosmium and I'm geting this error:
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0: undefined symbol: PyClass_Type

You can see it here:
https://travis-ci.org/Xevib/changewithin/jobs/221791372

The travis configuratio is this:
https://github.com/Xevib/changewithin/blob/8abbaa49ae720111fca9b54e153e196e04c14187/.travis.yml

I also tested it with a docker and I hav the same error

**Comment by lonvia** [comment]
You have linked against the wrong boost-python library. There is no boost-python library specifically for the 3.5 version in your system, so it falls back to the default libboost_python.so which happens to be the one for python 2.7. I'm not sure it is possible to easily install a matching boost-python version in travis. You might have to fall back to testing against the default python 3.4.

**Comment by Xevib** [comment]
Thank you Sarah, with Python 3.4 works fine
