### ISSUE TITLE
PyOsmium on Windows

### ISSUE THREAD

**Issue by joto** [osmcode/pyosmium#34]
In theory PyOsmium should work on Windows, but I don't think anybody ever tried.

@alex85k Do you want to try this out and maybe get an Appveyor config going?

**Comment by alex85k** [comment]
I have tried, it needs some patches on library-finding (or hardcoding), dininot manage to make it use my static boost for now.

**Comment by alex85k** [comment]
Managed to fix libraries (mostly hardcoding for now), it installs but does not find any classes when running:
```
TypeError: No Python class registered for C++ class class osmium::Way
```
Maybe I'll have more luck with python3, not 2.7.

**Comment by alex85k** [comment]
The "No Python class registered" was because of static boost libs (static boost.python3 gave the same error). Fixed whe I built it with dynamically-licked boost.

Now it compiles but wants dll in paths and fails one test.
Will create a WIP pull-request to share.

**Comment by joto** [comment]
@springmeyer Can you activate Appveyor for this repository so that we can tests the work from @alex85k ?

**Comment by alex85k** [comment]
Yes, now working on devpack...

**Comment by springmeyer** [comment]
Added: https://ci.appveyor.com/project/Mapbox/pyosmium
