### ISSUE TITLE
SimpleWriter add_way encountered MemoryError

### ISSUE THREAD

**Issue by chrisail** [osmcode/pyosmium#37]
Hi

I actually use `SimpleWriter` class in order to persist isolines generated by GDAL contour function.

I use "OsmObject" class like in example
```
class OsmObject(object):
    def __init__(self, **params):
        for k,v in params.items():
            setattr(self, k, v)
```
And than for each isoline, add way like below. `nodes_ids` is the array that contains ids of previously written nodes.
```
tags = {attr_name: str(int(altitude)), "contour": "elevation", "contour_ext": contour_ext, "id": str(ways_counter), "nodesnm": str(len(nodes_ids))}
pbf_writer.add_way(OsmObject(id=ways_counter, nodes=nodes_ids, tags=tags, version=1))
```
My problem is when I generate a huge amount of ways (3 739 825 when last error occurs), I've got a memory error, always when writing ways. I made several tests with more available memory. It shows that more memory I have, later the problem occurs. I use Python 3.5 on Ubuntu.

> Traceback (most recent call last):
>   File "generatesrtmosm.py", line 395, in <module>
>     create_isolines(hgtfile, base_filename, args.i)
>   File "generatesrtmosm.py", line 82, in create_isolines
>     add_way(gen_feat, bbox, pbf_writer)
>   File "generatesrtmosm.py", line 122, in add_way
>     process_points(final_linestring.GetPoints(), altitude, contour_ext)
>   File "generatesrtmosm.py", line 146, in process_points
>     pbf_writer.add_way(OsmObject(id=ways_counter, nodes=nodes_ids, tags=tags, version=1))
> MemoryError

In attachement, a line chart that shows memory consumption during my processing.
In this example, I want to generate isolines for Mexico: 260 HGT files to process.
For each HGT file, I call GDAL contour function, then I use the result to add nodes and associated ways.
I close the writer only at the end of the processing.
We can see memory consumption behavior on next chart.
![srtmosm](https://cloud.githubusercontent.com/assets/18008107/25635327/063d58e6-2f7e-11e7-917a-97a2a96638c2.png)

It seems that this behavior change when PBF file size is more than 1 Gb. 1.8 Gb when last error occurs.

Does I misunderstand something? Does the amount of nodes and ways is too huge for pyosmium ?

I would appreciate to have an explanation about my current problem.

Thank you.

**Comment by chrisail** [comment]
Thank you for your help.

1. I saw an error in my Python code (SimpleWriter instance wasn't marked global in a function).  So I decided to test it again. For now, 112 HGT has been processed on 260 and the behavior seems to be the same. I'm waiting for error.
2. After, I will use a SimpleWriter with a bigger buffer.
3. Then, I will test with your change. I hope I will succeed in compiling your code. Actually, I use the automatic install.

Yesterday, I also mimic generation of 5 000 000 ways with 2 000 nodes for each way. No problems.

I will give you more information after having complete tests.

**Comment by chrisail** [comment]
Hi Sarah, 
I reproduced the error with the code below :

```
import osmium as o
import os, psutil

class OsmObject(object):
    def __init__(self, **params):
        for k,v in params.items():
            setattr(self, k, v)

if __name__ == "__main__":
    process = psutil.Process(os.getpid())
    print("MEM at init : ", process.memory_info().rss)

    pbf_writer_name = "/home/xx/Maps/hugefile.osm.pbf"
    if os.path.exists(pbf_writer_name):
        os.remove(pbf_writer_name)

    pbf_writer = o.SimpleWriter(pbf_writer_name)

    # id start as the same position than in my original code
    global_nodes_counter = 10000000
    global_ways_counter = 10000000

    # For Mexico, I have 260 HGT, with a mean of 24 000 ways
    for hgt_counter in range(0, 260):
        for way_counter in range(0, 24000):
            nodes_ids = []
            # 2000 is the upper limit of nodes by way (when managing contour lines created by GDAL)
            for node_counter in range(0, 2000):
                # Add node to output osm.pbf & increment nodes counter
                pbf_writer.add_node(OsmObject(id=global_nodes_counter, location=(1.111111, 43.111111), version=1))
                nodes_ids.append(global_nodes_counter)
                global_nodes_counter += 1

            tags = {"elev": str(int(100)), "contour": "elevation", "contour_ext": "elevation_minor",
                    "id": str(global_ways_counter), "nodesnm": str(len(nodes_ids))}
            pbf_writer.add_way(OsmObject(id=global_ways_counter, nodes=nodes_ids, tags=tags, version=1))
            global_ways_counter += 1

        print("HGT {0} - MEM Usage : {1}".format(hgt_counter + 1, process.memory_info().rss))

    pbf_writer.close()
    print("global_ways_counter = {0} / global_nodes_counter = {1}".format(global_ways_counter, global_nodes_counter))
```

It's generate the error :
```
xx@xx:~$ python3.5 /home/xx/PycharmProjects/TestOsmium/osmhugepbfwrite.py
MEM at init :  16928768
HGT 1 - MEM Usage : 237899776
HGT 2 - MEM Usage : 91090944
HGT 3 - MEM Usage : 1018286080
HGT 4 - MEM Usage : 873340928
HGT 5 - MEM Usage : 728633344
HGT 6 - MEM Usage : 1654263808
Traceback (most recent call last):
  File "/home/xx/PycharmProjects/TestOsmium/osmhugepbfwrite.py", line 36, in <module>
    pbf_writer.add_way(OsmObject(id=global_ways_counter, nodes=nodes_ids, tags=tags, version=1))
MemoryError
xx@xx:~$ 
```

Do you obtain the same result?

Thank you for your help.

**Comment by lonvia** [comment]
Thanks for creating a test case. I've just tried and I get a perfectly bound memory usage:

```
MEM at init :  16650240
HGT 1 - MEM Usage : 29614080
HGT 2 - MEM Usage : 29614080
HGT 3 - MEM Usage : 29884416
HGT 4 - MEM Usage : 29884416
HGT 5 - MEM Usage : 29884416
HGT 6 - MEM Usage : 29884416
HGT 7 - MEM Usage : 29884416
```

Is it possible that there was still a trace of the older pyosmium version left? I'm about to release a new version tonight. Can you try with that later?

**Comment by chrisail** [comment]
Hi Sarah,
I really appreciate your help.

I'm not comfortable with Python and Linux and yesterday, I made an error when I built and installed last branch. **I'm under Python3 and forgot "3"** on command line.

So, for newbies like me, if you are under Python3, you should install Pyosmium like this:
```
git clone git://github.com/osmcode/pyosmium.git
cd pyosmium/
git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
sudo python3 setup.py build
sudo python3 setup.py install
```
For now, on test case, it works fine:
```
MEM at init :  17039360
HGT 1 - MEM Usage : 30539776
HGT 2 - MEM Usage : 30691328
HGT 3 - MEM Usage : 30691328
HGT 4 - MEM Usage : 30691328
HGT 5 - MEM Usage : 30691328
HGT 6 - MEM Usage : 30691328
HGT 7 - MEM Usage : 30691328
HGT 8 - MEM Usage : 30691328
HGT 9 - MEM Usage : 30691328
```

**Currently, contour lines generation for Mexico is in progress.
I hope that I will be able to give you the good news this evening.
Thank you.**

**Comment by lonvia** [comment]
No worries, I'm glad to see the test case works for you now, too. Your installation steps are correct but please don't use `sudo` for the build step.

In any case, the new release is out and contains the fix, so you should be able to go back to using `pip3 install -U osmium`.
