### ISSUE TITLE
None of the callbacks are called from apply_diff()

### ISSUE THREAD

**Issue by nyurik** [osmcode/pyosmium#38]
See the issue and sample code at https://stackoverflow.com/questions/44170360/callbacks-not-called-in-pyosmiums-diff-downloader

Note that the exact same handler works fine when used from `handler.apply_file()`

CCing: For some reason, this code does not print any nodes, ways, or relations, even though it clearly does download the minute updates from OpenStreetMap:

    import logging
    import osmium
    from osmium.replication.server import ReplicationServer

    logging.basicConfig(level=logging.DEBUG)

    class Handler(osmium.SimpleHandler):
        def __init__(self):
            super(Handler, self).__init__()

        def node(self, n):
            print('n', n.id)

        def way(self, w):
            print('w', w.id)

        def relation(self, r):
            print('r', r.id)

    h = Handler()
    rs = ReplicationServer('http://planet.openstreetmap.org/replication/minute')
    rs.apply_diffs(h, 2112110, 0.4*1024)

Result:

    /usr/bin/python3 /home/yurik/dev/osm2rdf/osm2rdf.py
    DEBUG:pyosmium:Downloaded change 2112110. (86 kB available in download buffer)
    DEBUG:pyosmium:Downloaded change 2112111. (36 kB available in download buffer)
    DEBUG:pyosmium:Downloaded change 2112112. (4 kB available in download buffer)
    DEBUG:pyosmium:Downloaded change 2112113. (-139 kB available in download buffer)
    
    Process finished with exit code 0

**Comment by lonvia** [comment]
I've just made a new release for the fixed version which you should now be able to install via pip.

**Comment by nyurik** [comment]
@lonvia thanks,works great!  (compiled from source, haven't tried pip)
