### ISSUE TITLE
Use nodecache with areas

### ISSUE THREAD

**Issue by fredericbonifas** [osmcode/pyosmium#40]
I am trying to cache nodes in order to use them when parsing an area. I have tried to adapt the example given: https://github.com/osmcode/pyosmium/blob/master/examples/use_nodecache.py

While this works fine with `way` objects, I don't manage to get it working to parse an `area` object. My guess is that it fails because the `area` is not a native OSM object but I am unsure. The code I am trying to get working is below:

``` python
import osmium as o
import sys

class WayHandler(o.SimpleHandler):

    def __init__(self, idx):
        super(WayHandler, self).__init__()
        self.idx = idx

    def area(self, a):
        print('area parsing')
        for outer_ring in a.outer_rings():
            for n in outer_ring.nodes:
                n.lat, n.lon # throws an exception if the coordinates are missing
                loc = idx.get(n.ref)
                print(loc)

if len(sys.argv) != 3:
    print("Usage: python create_nodecache.py <osm file> <node cache>")
    exit()

reader = o.io.Reader(sys.argv[1])

idx = o.index.create_map("sparse_file_array," + sys.argv[2])
lh = o.NodeLocationsForWays(idx)
lh.ignore_errors()

o.apply(reader, lh, WayHandler(idx))

reader.close()
```

What would be the best way to use nodecache when parsing an `area`?

**Comment by lonvia** [comment]
You don't need to explicitly create the node cache. pyosmium will implicitly create and use one when you have an `area` callback. If you want to change the kind of nodestore (in particular, when you want to make it persistent) use the `idx` parameter for apply_file as described in the [Handling Geometries section](http://docs.osmcode.org/pyosmium/latest/intro.html#handling-geometries).

So your example above would look like:

```
import osmium as o
import sys

class WayHandler(o.SimpleHandler):

    def area(self, o):
        # do stuff here

WayHandler().apply_file(sys.argv[1], idx="sparse_file_array," + sys.argv[2])
```

**Comment by fredericbonifas** [comment]
Ok thank you very much @lonvia !
