### ISSUE TITLE
Unexpected no-error crash with invalid idx parameter

### ISSUE THREAD

**Issue by nyurik** [osmcode/pyosmium#42]
Setting `idx` to `dense_mmap_array` with a filename causes a fatal crash after a long delay, without any error messages or stacktraces.  Took me a while to figure it out, as I wasn't even sure where the crash takes place.

`ttlFile.apply_file(pbfFile, locations=True, idx='dense_mmap_array,test.nodecache')`

Example code -- run it with a small OSM PBF file as the first parameter.

```python
import sys
import osmium

class RdfHandler(osmium.SimpleHandler):
    def __init__(self):
        osmium.SimpleHandler.__init__(self)
    def __enter__(self):
        return self
    def __exit__(self, exc_type, exc_value, traceback):
        pass

if __name__ == '__main__':
    pbfFile = sys.argv[1]
    with RdfHandler() as ttlFile:
        ttlFile.apply_file(pbfFile, locations=True, idx='dense_mmap_array,test.nodecache')
```

**Comment by lonvia** [comment]
I see an error as expected:

```
me@machine:~$ python3 test.py liechtenstein-latest.osm.pbf 
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    ttlFile.apply_file(pbfFile, locations=True, idx='dense_mmap_array,test.nodecache')
RuntimeError: mremap failed: Cannot allocate memory
```

Is it possible that the application was killed by the OOM killer before it could error out properly?

**Comment by nyurik** [comment]
Very strange - I'm running `Python 3.5.3` on `Ubuntu 17.04`:
```bash
$ python3 bug.py liechtenstein-latest.osm.pbf
Killed
$
```

**Comment by lonvia** [comment]
Check your system logs if OOM was invoked.

**Comment by nyurik** [comment]
Ah, yes, thanks @lonvia, I wasn't aware of it. Does it mean that there is no easy way for python to report an OOM error/stack trace/something helpful?  Also, we might want to document various mem settings in more details. Thanks for your help!

**Comment by lonvia** [comment]
Unfortunately, there is nothing we can do about it. python gets killed the hard way in this case.

The mem settings are described in the [osmium concept manual](http://osmcode.org/osmium-concepts/#indexes). I've added a link to the section in the documentation now.
