### ISSUE TITLE
Should list types support the subscript operator

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#44]
It looks like the custom `*List` types do not support the subscript operator e.g.

```python
def relation(_, r):
    if len(r.members) != 3:
        return

    print(r.members[1])
```

does not work since the `RelationMemberList` does not support indexing.

Is there a reason for leaving out this feature or is it just an oversight?

cc @lonvia

**Comment by lonvia** [comment]
The indexing operator is only implemented where libosmium offers index access natively. The relation member collection offers only iterators. I prefer that users are aware of that fact.

**Comment by daniel-j-h** [comment]
I was not aware of that fact :) thanks, makes sense!

I'm wondering why the `RelationMemberList` does not support index access, though - should I open a upstream ticket or is there a reason behind it?

Closing here already anyway.

**Comment by lonvia** [comment]
Relation members don't have a fixed size because they contain a variable length string for the role. So O(1) indexed access is not possible.
