### ISSUE TITLE
fatal error: protozero/types.hpp: No such file or directory

### ISSUE THREAD

**Issue by baditaflorin** [osmcode/pyosmium#48]
Using ubuntu 16.04

python setup.py build
Using global libosmium.
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/osmium
copying src/osmium/version.py -> build/lib.linux-x86_64-2.7/osmium
copying src/osmium/__init__.py -> build/lib.linux-x86_64-2.7/osmium
creating build/lib.linux-x86_64-2.7/osmium/osm
copying src/osmium/osm/__init__.py -> build/lib.linux-x86_64-2.7/osmium/osm
copying src/osmium/osm/mutable.py -> build/lib.linux-x86_64-2.7/osmium/osm
creating build/lib.linux-x86_64-2.7/osmium/replication
copying src/osmium/replication/utils.py -> build/lib.linux-x86_64-2.7/osmium/replication
copying src/osmium/replication/server.py -> build/lib.linux-x86_64-2.7/osmium/replication
copying src/osmium/replication/__init__.py -> build/lib.linux-x86_64-2.7/osmium/replication
running build_ext
building 'osmium._osmium' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/lib
c++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include -I/usr/include/python2.7 -c lib/osmium.cc -o build/temp.linux-x86_64-2.7/lib/osmium.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
In file included from /usr/local/include/osmium/io/pbf_output.hpp:46:0,
                 from /usr/local/include/osmium/io/any_output.hpp:50,
                 from lib/generic_writer.hpp:6,
                 from lib/osmium.cc:7:
/usr/local/include/osmium/io/detail/pbf_output_format.hpp:47:31: fatal error: protozero/types.hpp: No such file or directory
compilation terminated.
error: command 'c++' failed with exit status 1

**Comment by lonvia** [comment]
The supplied libosmium and protozero in Ubuntu 16.04. are far too old. Use pip to install pyosmium on theses systems (`pip install osmium`).

**Comment by lonvia** [comment]
pip install is now mentioned in the README.
