### ISSUE TITLE
Build and distribute pyosmium wheel

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#49]
Do you think it makes sense to build and distribute a Python Wheel for PyOsmium? At the moment users need to install build-essentials, all libosmium native deps, and boost-python-dev.

Would it make sense to build a wheel and ship it, so that users can simply

    pip install osmium

and don't have to worry about dependency management?

(FYI: this is food for thought, not urgent or blocking - I noticed this while bundling a pyosmium program with Docker and was a bit surprised how much I have to pull in to get pyosmium to compile)

Here are some notes with refs to get started:
- https://github.com/scanse/sweep-sdk/issues/54
- https://github.com/scanse/sweep-sdk/pull/51

and it's a bit tricky with native deps as usual :)

**Comment by lonvia** [comment]
This would absolutely make sense but I don't currently have the resources to build and test this sufficiently. Leaving this issue open anyway, just in case somebody wants to pick it up.

**Comment by wiktorn** [comment]
I'm giving this a look. After some preliminary testing it looks like [manylinux](https://github.com/pypa/manylinux) / [PEP513](https://www.python.org/dev/peps/pep-0513/) is a way to go. Just simple move from one Ubuntu release to the other breaks standard wheel because of difference in version of boost library.

The only drawback of using manylinux is that this is very conservative environment with gcc 4.8, boost 1.41 which are quite old.

I still haven't tested how standard wheels behave on Windows and macOS, but looking at this [ticket ](https://bugs.python.org/issue32516) I fear that it might be not that easy with Windows.

As for testing - I plan to use Travis /AppVeyor to build a wheel, and then run test suite in separate virtualenv, after, if possible, deinstallation of system-wide build packages (boost, boost-python etc.).

**Comment by joto** [comment]
PyOsmium uses libosmium which doesn't work with boost 1.41 and I am not sure it all works with GCC 4.8.

**Comment by wiktorn** [comment]
Sorry, boost 1.48. At least it didn't complain during compilation, though I have problems during linking phase. Gcc 4.8 is used by travis builds so I assume, that’s what it works. Question is, how long we want to stick to it. 

OTOH I could just run auditwheel on Ubuntu trusty/xenial and see on how many platforms it will work

**Comment by mehdisadeghi** [comment]
I can test it on Mac provided the instructions.

**Comment by bnaul** [comment]
@wiktorn I'd suggest taking a look at https://github.com/matthew-brett/multibuild, I've used these tools to build OS X + manylinux wheels for a couple of packages w/ minimal effort.

You might also take a look at [the ray project](https://github.com/ray-project/ray/blob/a24cc287735b4d8da6778cca9d49d8a06947e42c/python/README-building-wheels.md) which builds manylinux wheels that use boost.

**Comment by wiktorn** [comment]
@bnaul Thank's a lot, that could help a lot.

Just as I got manylinux wheels up & running on Debian / Ubuntu / Centos / Arch.

**Comment by wiktorn** [comment]
Looks like I've got it working on Linux & macOS with Travis.

On Linux I build manylinux binaries using Boost 1.67 compiled from source (as CentOS 5 has outdated Boost). Using Docker build is tested on:

Distribution | Python 2 | Python 3
-----------------|--------------|-------------
Debian (stretch / latest) | 2.7  | 3.5
Ubuntu (bionic / latest) | 2.7 | 3.6
Centos (centos7 / latest) | 2.7 | 3.4
ArchLinux (latest) | 2.7 | 3.6

It should be fairly easy to add additional distributions to test. Though they are only x64.

On macOS builds use Boost  provided by HomeBrew but I'm afraid that wheel will be pinned to specific Boost version and will fail to load if there is no specific version of Boost available on system. I'm not sure, if it's an improvement.

@lonvia Travis CI doesn't store any build artifacts. I tried uploads to AWS S3 and as a GitHub release. Both has some drawbacks - AWS needs an account there, GitHub releases are created per job, so for one build - you get 6 releases. You can always use your own build infrastructure. Which way you plan to go with this?

Next I plan to check Windows builds.

Should I test any other distributions? Anything else that should be done?

**Comment by wiktorn** [comment]
Waiting for @lonvia to finish replacing boost-python with pybind11 and then this will be far easier to build and distribute

**Comment by lonvia** [comment]
@wiktorn What is the status on this? You said that you wanted to do some more testing. Given the rather large changes with pybind11 and the binary wheels, I'd like to roll out an exceptional pre-release, so that we can get a bit more feedback before the next full release. Also would help to test the whole workflow of wheel creation.

**Comment by wiktorn** [comment]
I've did some tests installing binary wheel from this release:
https://github.com/osmcode/pyosmium-wheel-build/releases/tag/untagged-2289a1529af3fba1b920

Success:
```#!bash
# Python2
docker run -it --rm -v /home/w/Downloads:/io ubuntu:latest /bin/bash -c "apt update && apt install -y python-pip && pip install nose mock && pip install --no-index osmium --find-links /io && cd /io/test && python -m nose && python -V"
docker run -it --rm -v /home/w/Downloads:/io debian:latest /bin/bash -c "apt update && apt install -y python-pip && pip install nose mock && pip install --no-index osmium --find-links /io && cd /io/test && python -m nose && python -V"
docker run -it --rm -v /home/w/Downloads:/io fedora:latest /bin/bash -c "yum install -y python-pip && pip install nose mock && pip install --no-index osmium --find-links /io && cd /io/test && python -m nose && python -V"
docker run -it --rm -v /home/w/Downloads:/io base/archlinux:latest /bin/bash -c "pacman -Sy --noconfirm python2-pip && pip2 install nose mock && pip2 install --no-index osmium --find-links /io && cd /io/test && python2 -m nose && python2 -V"


# Python3
docker run -it --rm -v /home/w/Downloads:/io ubuntu:latest /bin/bash -c "apt update && apt install -y python3-pip && pip3 install nose mock && pip3 install --no-index osmium --find-links /io && cd /io/test && python3 -m nose"
docker run -it --rm -v /home/w/Downloads:/io debian:latest /bin/bash -c "apt update && apt install -y python3-pip && pip3 install nose mock && pip3 install --no-index osmium --find-links /io && cd /io/test && python3 -m nose"
docker run -it --rm -v /home/w/Downloads:/io fedora:latest /bin/bash -c "yum install -y python3-pip && pip3 install nose mock && pip3 install --no-index osmium --find-links /io && cd /io/test && python3 -m nose && python3 -V"
docker run -it --rm -v /home/w/Downloads:/io base/archlinux:latest /bin/bash -c "pacman -Sy --noconfirm python-pip && pip install nose mock && pip install --no-index osmium --find-links /io && cd /io/test && python -m nose && python -V"
```                  

Failure:
```
# Python2:
docker run -it --rm -v /home/w/Downloads:/io alpine:latest /bin/ash -c "apk update && apk add py2-pip && pip install nose mock && pip install --no-index osmium --find-links /io && cd /io/test && python -m nose && python -V"


# Python3
docker run -it --rm -v /home/w/Downloads:/io alpine:latest /bin/ash -c "apk update && apk add py3-pip && pip3 install nose mock && pip3 install --no-index osmium --find-links /io && cd /io/test && python3 -m nose && python3 -V"
```     

But after thinking this through again it's natural that this wheels fail on Alpine Linux - it uses libmusl instead of glibc.

**Comment by lonvia** [comment]
Do binary wheels of other python packages work on Alpine Linux?

**Comment by wiktorn** [comment]
As far as I've checked - no (officially). They may work if you install glibc on Alpine Linux and set your installation as manylinux compatibile (see pypa/pip#3969). So I guess it's not a showstopper.

I guess that for Alpine it would be the best to provide apk binary package.

**Comment by lonvia** [comment]
The latest 2.15.0 release now ships with binary wheels. Many thanks to @wiktorn for pushing this forward.
