### ISSUE TITLE
FreeBSD build

### ISSUE THREAD

**Issue by sporkman** [osmcode/pyosmium#55]
Using either pip or building from source fails.  It looks like the way the boost libs or searched for is very linux-specific, so it doesn't find the installed boost libs.  Errors for each type of build below.  On installing the python boost libs, I'm given this message with instructions for linking:

```
You have built the Boost.Python library. You have to add the following
options when building your own code:

Compiler options:
   -I/usr/local/include/python2.7 -I/usr/local/include

Linker options:
   -L/usr/local/lib/python2.7 -L/usr/local/lib -lboost_python -lpython2.7
```
Not sure how to fiddle with setup.py to get pyosmium looking in the right place.  Any tips?

Pip and source build attempts below:

```
[root@nominatim ~]# pip install osmium
Collecting osmium
  Using cached osmium-2.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oVEgyO/osmium/setup.py", line 74, in <module>
        raise Exception("Cannot find boost_python library")
    Exception: Cannot find boost_python library

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oVEgyO/osmium/
```

```
[spork@nominatim ~/osmium-2.13.0]$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    raise Exception("Cannot find boost_python library")
Exception: Cannot find boost_python library
```

**Comment by lonvia** [comment]
Looks like you have manually installed Boost into `/usr/local`. Try setting BOOST_PREFIX (`export BOOST_PREFIX=/usr/local`) and repeat the installation.

**Comment by sporkman** [comment]
Same error.  Everything is installed via the package manager, pkg.  I have the actual boost libraries and the python bindings.  By default packages land in /usr/local.  This is to make a clear delineation between the base OS and installed packages.

Also, regarding your other rather personal comments on my skillset in the other thread, unless I'm mistaken, osmium is not a requirement to build/install nominatim, it's only used for updates, hence the two github issues - one for building this so in the future I can automatically update, and one to perhaps get the attention of the person that was working on adding nominatim to the ports tree.

Regardless, if you don't see value on this running outside the Linux ecosystem, please tell me to stop spending my time troubleshooting this.  I'm working on a volunteer basis with non-profits on a project that would benefit from a local install of nominatim.  I don't need hostility when asking for help.  I am not a python guy by a long shot, sorry.  I can say setup.py is nowhere near being OS-agnostic just looking at all the hardcoded paths in there.

Here are the python and boost packages that are installed:

```
[spork@nominatim ~]$ pkg info | grep boost
boost-jam-1.65.1               Build tool from the boost.org
boost-libs-1.65.1_1            Free portable C++ libraries (without Boost.Python)
boost-python-libs-1.65.1       Framework for interfacing Python 2 and C++
[spork@nominatim ~]$ pkg info | grep python
boost-python-libs-1.65.1       Framework for interfacing Python 2 and C++
python-2.7_3,2                 "meta-port" for the default version of Python interpreter
python2-2_3                    The "meta-port" for version 2 of the Python interpreter
python27-2.7.14_1              Interpreted object-oriented programming language
```

**Comment by lonvia** [comment]
From the information you gave, `BOOST_PREFIX` should have done the trick. If it still doesn't work, then `find_library()` is not doing the right thing on FreeBSD. That would be rather a Python issue than one for pyosmium. On Linux I would recommend playing with LD_LIBRARY_PATH but I have no idea how these things work in FreeBSD. If you find a work around, feel free to report how you have solved the issue and we can see if something can be hacked into setup.py. But for finding the solution you are on your own, sorry.

**Comment by sporkman** [comment]
Just a few updates:

- If I manually define where the boost libraries live and comment out all the automated bits, the libraries are found and all is well
- Not seeing any obvious reason why it fails
- I'm going to try making a little standalone "find_library()" test to see if I can understand what's happening

**Comment by sporkman** [comment]
OK, this very stripped-down example works:

```
[spork@nominatim ~]$ cat test.py
import ctypes
import ctypes.util
boostlib = ctypes.util.find_library("boost_python")
print boostlib

[spork@nominatim ~]$ python test.py
libboost_python.so.1.65.1
[spork@nominatim ~]$
```

**Comment by kkdd** [comment]
Hello,
In macOS, ```find_library``` prints the following:

```
$ uname
Darwin
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
$ python3
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('boost_python36')
'/usr/local/lib/libboost_python36.dylib'
```

**Comment by lonvia** [comment]
@sporkman Could you quickly check if the latest release works for you?

**Comment by wiktorn** [comment]
I've just checked on `FreeBSD 11.1-RELEASE-p8`. The problem persists. I've managed to solve it by:
```sh
# ln -s /usr/local/lib/libboost_python36.so.1.67.0 /usr/local/lib/libboost_python36.so.1
```
And then
```sh
$ BOOST_PREFIX=/usr/local ./venv/bin/pip install osmium
```

To me it looks like a problem in either libboost_python or ctypes. Quite a few libraries are missing symlinks with major version on FreeBSD.

**Comment by lonvia** [comment]
Okay, thanks for checking. Would it help add an optional BOOST_VERSION environment variable and then check for a more specific `libboost_python36.so.<BOOST_VERSION>`?

**Comment by wiktorn** [comment]
Regrettably this won't help. For some reason this missing symlink results in `ldconfig` cache missing boost libraries. `ctypes.utils.find_library` on FreeBSD depends on ldconfig cache to find libraries.

This bug could be labelled with "other software" label and kept open until FreeBSD ports is fixed for others that will bump on this.

**Comment by lonvia** [comment]
Too bad. This is really a FreeBSD issue then. Closing here as invalid. If you find in the future that the pyosmium's setup script can do something helpful for a situation like this, feel free to open a new issue.

**Comment by koobs** [comment]
@wiktorn See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227939
