### ISSUE TITLE
osmium package in python 3.6 links to libboost for 2.7

### ISSUE THREAD

**Issue by culebron** [osmcode/pyosmium#56]
Here's my traceback of failed import. The python script is executed in 3.6, just as osmium package. But osmium opens `libbost_python-py27` and fails:

        import osmium as osm
      File "/usr/local/lib/python3.6/dist-packages/osmium/__init__.py", line 1, in <module>
        from osmium._osmium import *
    ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0: undefined symbol: PyClass_Type

There is `/usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0` file in the same directory (`/usr/lib/x...gnu/`), which probably should work with 3.6.

Libboost was installed with pip3:

    sudo pip3 install libboost

(when installed locally, the issue is the same)

How to fix this?

**Comment by lonvia** [comment]
Same as #52. The setup script is not able to detect the version mismatch here and will fall back to whatever libboost_python.so points to. You must have a boost library installed that matches your python version.
