### ISSUE TITLE
Cannot find boost_python library in python:alpine

### ISSUE THREAD

**Issue by mehdisadeghi** [osmcode/pyosmium#62]
Running `pip install osmium` fails with the above command in python:alpine docker image:

```
$ docker run -it python:alpine sh

/ # pip -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
/ # python --version
Python 3.6.4

/ # pip install osmium
Collecting osmium
  Downloading https://files.pythonhosted.org/packages/7a/eb/63d7af416ee6126c96a3e5c057750e266da5d1eecc108a6fe87cad9e98c9/osmium-2.14.1.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 229kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eyl31081/osmium/setup.py", line 81, in <module>
        raise Exception("Cannot find boost_python library")
    Exception: Cannot find boost_python library
```

Installing `boost-python` or `boost-python3` did not help:

```
/ # apk add boost-python3
(1/3) Installing python3 (3.5.2-r2)
(2/3) Installing libgcc (5.3.0-r0)
(3/3) Installing boost-python3 (1.60.0-r2)

/ # ls /usr/lib/libboost*
/usr/lib/libboost_python3-mt.so.1.60.0  /usr/lib/libboost_python3.so.1.60.0
```

I also tried linking the `.so` files to `libboost_python.s` but it didn't help.

I appreciate any comments on this.

**Comment by lonvia** [comment]
Could you please try with the latest version from master.

**Comment by mehdisadeghi** [comment]
> Could you please try with the latest version from master.

I tried, it didn't make any difference. I also installed `boost` and `boost-dev` to no avail.

**Comment by lonvia** [comment]
What does `sudo ldconfig -p | grep boost_python` return? (Replace `-p` with whatever option is appropriate for listing the cache, if your ldconfig has different command line options.)

**Comment by mehdisadeghi** [comment]
`ldconfig` in alpinelinux has no `-p` or any other options. 

I think even fixing the issue with libboost_python will not help. Alpinelinux uses [musl-libc](https://www.musl-libc.org/) and I think the question is whether it is possible to build libosmium in alpinelinux at all. My naive try to compile it under Alpinelinux was unsuccessful, due to many missing compile tools. 

We can leave this issue open for future visitors or simply close it as won't fix.

**Comment by lonvia** [comment]
pyosmium needs `find_library` to work on your system and I suspect that this is not the case without a proper `ldconfig`. This really needs fixing in the python installation of alpine linux first.

Closing as won't fix.
