### ISSUE TITLE
test_mercator_lonlat (test_geom.TestCoordinateConversion) fails on i386

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#68]
The Debian package build for pyosmium 2.14.2 failed on i386 due to a test failure:
```
======================================================================
FAIL: test_mercator_lonlat (test_geom.TestCoordinateConversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_geom.py", line 65, in test_mercator_lonlat
    assert_equals(c.y, 0)
AssertionError: 3.5097917871618886e-15 != 0

----------------------------------------------------------------------
```

Full buildlog: [i386](https://buildd.debian.org/status/fetch.php?pkg=pyosmium&arch=i386&ver=2.14.2-1&stamp=1533623121&file=log)

**Comment by lonvia** [comment]
I have pushed a fix in 8450ad7. Do you mind checking that this really resolves the issues before I do another release? I can't really reproduce it here.

**Comment by sebastic** [comment]
Thanks for the quick fix, confirmed fixed on i386.

**Comment by lonvia** [comment]
Thanks for testing. I've made a bug fix release.
