### ISSUE TITLE
Fail to install on MacOS High Sierra

### ISSUE THREAD

**Issue by mvexel** [osmcode/pyosmium#70]
[This](https://gist.github.com/mvexel/3e49cd2c98381bcad759ab4e5a0163db) happens.

I don't think this is a pyosmium issue per se because very similar issues have been [reported upstream](https://github.com/Homebrew/homebrew-core/issues/18388).

However, I would like to know if anyone using PyOsmium on MacOS High Sierra with XCode 9 found a workaround for this.

Thank you!

**Comment by joto** [comment]
I fixed some of the warnings in #71, but that is the least of your problems. I can't find anything wrong with the PyOsmium or libosmium code. This is an issue with XCode it seems.

Might be related: https://github.com/sass/libsass-python/issues/240

**Comment by mvexel** [comment]
Thanks. Yes, it does seem to be an XCode problem where it somehow prefers the standard C `math` library rather than a c++ one.. I don't quite understand since I know so little about the c++ compilation process..

Regardless -- removing XCode by simply moving the XCode application from `/Applications` to the trash solves the problem. Since homebrew relies on XCode a lot, I will probably [revert to an older version](https://stackoverflow.com/questions/14756026/how-to-downgrade-xcode-to-previous-version).

**Comment by drewda** [comment]
Thanks for this @mvexel -- your temporary solution of trashing XCode solved the problem for me as well.
