### ISSUE TITLE
[installation] protozero compilation error

### ISSUE THREAD

**Issue by mvexel** [osmcode/pyosmium#72]
This may be better reported upstream..Not sure. Sorry if this is not the right place.
Installing pyosmium I run into a compiler error when compiling `protozero`:

```
protozero found in 'protozero-1.6.3'.
x86_64-linux-gnu-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
error: Setup script exited with error: command 'x86_64-linux-gnu-g++' failed with exit status 4
```
My best guess is this is a memory constraint related error.. This is on a Linode 2G with (you guessed it) 2GB of RAM.

**Comment by joto** [comment]
From the error message in the other issue you created you can see that you don't have enough memory. Pyosmium and libosmium have a lot of templates so this is not entirely unexpected. Cross-compile on a different machine.
