### ISSUE TITLE
Wrong coordinates written by SimpleWriter

### ISSUE THREAD

**Issue by ruzhytskyi** [osmcode/pyosmium#83]
Node coordinates written to file by SimpleWriter() differ from location I've passed when creating Node() instance.
```
from osmium import SimpleWriter
from osmium.osm.mutable import Node

n = Node(location=(30.46, 50.37), id=1)
writer = SimpleWriter('osm.xml')
writer = SimpleWriter('osm.xml')
writer.add_node(n)
writer.close()
```
Result:
```
$ cat osm.xml 
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="libosmium/2.14.2">
  <node id="1" lat="50.3699989" lon="30.4599991"/>
</osm>
```
Osmium version: osmium==2.14.3
Python: 3.5.2
OS: Ubuntu 16.04.5

**Comment by lonvia** [comment]
The conversion of the location coordinates didn't keep sufficient precision. Fixed on master.

**Comment by ruzhytskyi** [comment]
Thank you! It works in master now.
