### ISSUE TITLE
Probleme with installing osmium

### ISSUE THREAD

**Issue by bidabil** [osmcode/pyosmium#84]
When trying to install osmium by using the command pip install osmium
Collecting osmium
  Using cached https://files.pythonhosted.org/packages/f1/74/4b06a023c19006133309bfbc5460bede50f451089c01ca7fa9caa1d06bf4/osmium-2.14.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZvtHId/osmium/setup.py", line 115, in <module>
        raise Exception("Cannot find boost_python library")
    Exception: Cannot find boost_python library

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZvtHId/osmium/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by lonvia** [comment]
See https://pypi.org/project/osmium/ about installing libboost.
