### ISSUE TITLE
Also support pybind11 2.0

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#86]
The backport for Debian stretch cannot be updated because that has pybind11 2.0.1, and pyosmium currently fails to build with that version (after patching the version requirement in `CMakeLists.txt`):
```
/build/pyosmium-2.15.0/lib/geom.cc:25:16: error: expected constructor, destructor, or type conversion before '(' token
 PYBIND11_MODULE(geom, m)
                ^
CMakeFiles/geom.dir/build.make:62: recipe for target 'CMakeFiles/geom.dir/lib/geom.cc.o' failed
```

Would it be possible to also support building with pybind11 2.0?

**Comment by lonvia** [comment]
This is tricky. PYBIND11_MODULE was only introduced in pybind11 2.2. I need to check if I can replace it with the previously used PYBIND11_PLUGIN for versions <2.2.

**Comment by lonvia** [comment]
So I managed to work around the missing PYBIND11_MODULE with some strategically placed defines and it compiles. But the tests don't pass. I could work around the issue where parameters are badly deduced when inheritance is involved. But then I run into issues with returning unique_ptr, likely a variant of https://github.com/pybind/pybind11/issues/641. I'm reluctant to dig further here. Even if I manage to make all tests pass, I'm not confident enough that they will find all issues and that such a version would really be usable.

If a more recent pybind11 is not an option for the backports, then you should be able to use a pyosmium 2.14.x with the newest libosmium 2.15.x without much loss of functionality. I can maintain the 2.14.x branch to ensure that compatibility until the next Debian is out, even backport bugfixes, if that helps. But pybind11 2.0 support does not look to be feasible.

**Comment by sebastic** [comment]
Thanks for trying to support 2.0. For the backport I'll use a patch to add pybind 2.2 in `contrib`.
