### ISSUE TITLE
ImportError: No module named _osmium

### ISSUE THREAD

**Issue by agude** [osmcode/pyosmium#9]
I compiled libosmium-2.5.4 and pyosmium-2.5.4 on Ubuntu 15.10 from scratch. After installing pyosmium, Python fails to import osmium with the error:

```
Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 18:04:42) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import osmium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "osmium/__init__.py", line 1, in <module>
    from ._osmium import *
ImportError: No module named _osmium
```

My `gcc` version is 5.2.1 (so violating the "You have to compile with the same compiler version python is compiled with on your system, otherwise it might not work."). I attempted to compile pyosmium with 4.4.7 to match my Python version but it fails.

Is this the "it might not work" failure mode for when the `gcc` versions are not matched, or is it a new issue?

**Comment by lonvia** [comment]
Are you in the pyosmium root directory while trying the import? Change the directory to somewhere else and try again. In the root directory the local osmium source directory takes precedence over your freshly installed version.

**Comment by agude** [comment]
Exactly the problem, thank you!
