### ISSUE TITLE
How to 'get-changes' for a specific set of tags?

### ISSUE THREAD

**Issue by themmes** [osmcode/pyosmium#91]
**Action**
The use case is keeping up to date a set of nodes that have the same tags. If I implement a filter in my Handler to only process nodes with specific tags, modifications to nodes changing the tags from relevant to non-relevant would not be processed.

**Attempts**
I know there exists the AugmentedDiff API (https://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs) however, I tried the ReplicationServer class with this API and it does not work. Which is expected I guess because the XML structure is somewhat different.

**Question**
Is there a different/better solution to my use case? Or is using the AugmentedDiffs the right approach but am I simply doing something wrong with the handler/replicationserver?

Thanks in advance!

**Comment by joto** [comment]
PyOsmium doesn't support augmented diffs.

But you can read normal change files (`.osc`). So you read the normal OSM (planet) file, filter out all nodes you want, keep their node IDs around somewhere. Then you can read the change files and check for nodes you have in your list of IDs.

**Comment by themmes** [comment]
Thanks Jochen for your quick reply!

I was hoping to avoid this solution, because my handler application and database are separated by Kafka topic. Meaning I have to forward updates to all nodes and ways (building footprints) to the topic and check indices on the database side.
