### ISSUE TITLE
osmium.osm.Way.ends_have_same_location() returns wrong value

### ISSUE THREAD

**Issue by ltog** [osmcode/pyosmium#93]
I think I have discovered a bug in `osmium.osm.Way.ends_have_same_location()`:

I run the following program (with either python2 or python3):

```python
import osmium
import sys 

class DetailInfoHandler(osmium.SimpleHandler):

    def __init__(self):
        super(DetailInfoHandler, self).__init__()
        self._way_showed = False

    def way(self, w): 
        if self._way_showed == False:
            self._way_showed = True
            print("id: OSM id of the object (read-only): " + str(w.id))
            print("ends_have_same_location(): True if the start and end node of the way are at the same location: " + str(w.ends_have_same_location()))

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python same_location_issue.py <osmfile>")
        sys.exit(-1)

    DetailInfoHandler().apply_file(sys.argv[1])
```

The first way in the attached file [liechtenstein-latest.osm.pbf.zip](https://github.com/osmcode/pyosmium/files/2912124/liechtenstein-latest.osm.pbf.zip) is https://www.openstreetmap.org/way/4781367 . For this way `ends_have_same_location()` returns `True` whereas I believe it should return `False` (or throw an exception?).

**Comment by lonvia** [comment]
You need to have the locations loaded for `ends_have_same_location()`. Use location=true with apply_file(). The documentation was actually wrong. It promised it would throw if no locations are present but that is not what the corresponding libosmium function does. I fixed that.
