### ISSUE TITLE
Unclear implications of using osmium.osm.Location.lat_without_check

### ISSUE THREAD

**Issue by ltog** [osmcode/pyosmium#96]
Hi @lonvia 

Could you add some explanations in the documentation about the difference in `osmium.osm.Location` between lat/lon with and without check at https://docs.osmcode.org/pyosmium/master/ref_osm.html#osmium.osm.Location ?

What happens in the variant with check if there is an invalid location? (Throwing of an exception maybe? Of what type then?) Can I hope for a performance gain when using the variant without check? How much would that approximately be? What are possible reasons for invalid locations and how common are they?

**Comment by lonvia** [comment]
I've amended the documentation to point to the exception raised.

Wrt performance: you save an if check every time the function is called. This might be noticable when going through a couple of million nodes but with all the overhead that python produces anyway likely not enough to be significant.
