### ISSUE TITLE
Problem with changeset callback

### ISSUE THREAD

**Issue by lucadelu** [osmcode/pyosmium#97]
Hi,

I'm trying to read changeset values from an history file cutted with osmium, from documentation it seems possible to use the changeset callback but with my simple code and a osh.pbf file it read nothing

```python
class CaiStatsHandler(osmium.SimpleHandler):
    """Class to parse CAI routes from OSM file"""
    def __init__(self):
        self.changes = []

    def changeset(self, c):
        self.changes.append(c)

csh = CaiStatsHandler()
csh.apply_file('sicilia.osh.pbf')
csh.changes
[]
```

I'm doing something wrong? Or is not possible to use osh file?

**Comment by joto** [comment]
PBF files can't contain changeset data. And you can't create exctracts from changesets. Changesets are read from XML files available at https://planet.openstreetmap.org/planet/ (look at changesets-latest.osm.bz2 and discussions-latest.osm.bz2).

Note that "changesets" are something different from "change files" (also called "diff files"). That can be confusing sometimes.

**Comment by lucadelu** [comment]
ok, I didn't know that changeset are not saved in extracts. I downloaded changesets-latest.osm.bz2, but I have a segmentation fault... any idea?

```python
class CaiStatsHandler(osmium.SimpleHandler):
    """Class to parse CAI routes from OSM file"""
    def __init__(self):
        osmium.SimpleHandler.__init__(self)
        self.comment = None
        self.user = None
        self.rels = []
        self.routes = {}
        self.ways = {}
        self.changes = []

    def changeset(self, c):
        if self.user:
            if self.user == c.user:
                self.changes.append(c)
  
    def set_variables(self, comment, user=None):
        """Set the useful variables for analysis
        
        :param str comment: the text in the comment to search
        :param str user: the name of the user
        """
        self.comment = comment
        self.user = user

csh = CaiStatsHandler()
csh.set_variables('#CAIOSM', 'lucadelu')
csh.apply_file('/home/lucadelu/changesets-181203.osm')
cha = csh.changes[0]
cha
Segmentation fault
```

However the changesets-latest.osm.bz2 contain the user information and the modified elements?

**Comment by joto** [comment]
Quoting from [the docs](https://docs.osmcode.org/pyosmium/latest/intro.html#reading-osm-data): "It is important to remember that the object references that are handed to the handler are only temporary. They will become invalid as soon as the function returns. Handler functions must copy any data that should be kept for later use into their own data structures. This also includes attributes like tag lists."

Your line `self.changes.append(c)` keeps such a reference. You  have to make a deep copy of all the stuff you'll need.

**Comment by lucadelu** [comment]
Ok thanks, sorry for the late answer. I have one last question, the elements modified in the changeset are not saved in the changesets-latest.osm.bz2 file?

**Comment by lonvia** [comment]
Segmentation fault is fixed. Pyosmium now throws a Runtime error.
