### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by JohannCR** [osmcode/pyosmium#98]
Hi,

I'm having problems with an install on conda3 on win10 with Python 3.6.5
pip install went ok but when importing (either in a py notebook or py module in /lib) I have this DLL load failed because of 
from osmium._osmium import *

I don't know if I'm missing dependencies or what... The page https://github.com/osmcode/pyosmium/blob/master/README.md is really unclear about windows.
So I checked, cmake, Boost, setuptools are  installed but
build-essential, libboost-dev, libexpat1-dev, zlib1g-dev, libbz2-dev don't want to install via pip, it says "Could not find a version that satisfies the requirement/no matching distribution found)

What can I try ? Thanks

**Comment by lonvia** [comment]
When you install via pip for Python 3.6, you should get a binary wheel that contains all necessary DLLs. You shouldn't need any additional packages. Is this a 32bit or 64bit machine? Can you please provide the full error message that you get?

**Comment by wiktorn** [comment]
I've just tried that and have the same error.  Binary wheel's for Windows ships only *pyd files, using [lucasg/Dependencies](https://github.com/lucasg/Dependencies) I found out, that our binary distribution depends on:
* zlib.dll
* expat.dll
* libbz2.dll

I guess, that to have fully independent binary wheel for Windows, we would need to include these three libraries in wheel - we can't assume, that they are installed on Windows system (contrary to Linux/macOS).

As for @JohannCR problem, you could probably easily fix by:
`conda install bzip2=1.0.6 expat=2.2.5 zlib=1.2.11`

**Comment by lonvia** [comment]
They are supposed to be included. If you check the 'after_test' part of the appveyor script, it shoudl in theory copy them to the right place for  setup.py bdist_wheel` to pick them up. I need to check why this does not work anymore.

**Comment by lonvia** [comment]
So that's another pybind11 regression.

**Comment by lonvia** [comment]
@wiktorn Can you test with the wheel from https://ci.appveyor.com/project/lonvia/pyosmium/builds/22953835 when its done?

**Comment by wiktorn** [comment]
@lonvia Tested with 3.7 - it works. Contents of 3.6 and 2.7 wheels looks also OK.

**Comment by lonvia** [comment]
Thanks for testing. The wheels are now available at pypi with the new release.

**Comment by JohannCR** [comment]
Thanks a lot to you both, all good now !

**Comment by EpipolarWagner** [comment]
Hi,
I seem to encounter a similar problem. 
import osmium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "somePath\osmium3.7\lib\site-packages\osmium\__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
However the expat.dll, zlib.dll and libbz2.dll is located in the somium folder. Install osmium via pip without any problem. I use windows 10, conda and python 3.7.6.
